import type {
  CustomerArchetypeDefinition,
  LocalizedSeed,
} from "./types";

type CustomerSeed = Omit<
  CustomerArchetypeDefinition,
  "nameKey" | "descriptionKey"
> &
  LocalizedSeed;

const customerSeeds = [
  {
    id: "customer.early-shift-regular",
    name: "Early-Shift Regular",
    description:
      "Arrives early, knows what they want, values familiar breakfasts, and leaves quickly when a short queue stops moving.",
    gameplayRole: "Early-day throughput test",
    budgetRange: [5, 10],
    patienceSeconds: 52,
    walkingSpeedTilesPerSecond: 2.05,
    priceSensitivity: 0.68,
    qualitySensitivity: 0.48,
    queueSensitivity: 0.8,
    distanceSensitivity: 0.56,
    noveltyPreference: 0.15,
    seatPreference: "near-stall",
    dishPreferenceTags: ["breakfast", "coffee", "comfort", "rice"],
    groupSizeRange: [1, 2],
    visualRules: {
      bodyFrames: ["adult-a", "adult-b", "adult-c", "adult-d"],
      clothingPalettes: ["workwear-cool", "workwear-warm", "neutral-light"],
      accessoryChance: 0.28,
      carryProp: "tote",
    },
    visitSchedule: { startHour: 6, endHour: 11, peakMultiplier: 1.7 },
    satisfactionModifiers: {
      value: 0.16,
      speed: 0.24,
      comfort: 0.02,
      variety: -0.08,
      cleanliness: 0.08,
    },
    spendMultiplier: 0.9,
    trayReturnChance: 0.82,
    unlockRequirement: { level: 1, reputation: 0, prerequisiteIds: [] },
    tags: ["morning", "solo", "fast-turnover"],
  },
  {
    id: "customer.office-lunch-sprinter",
    name: "Office Lunch Sprinter",
    description:
      "Visits in the lunch rush with a firm time budget, preferring fast service and a seat close to the chosen stall.",
    gameplayRole: "Peak-hour queue pressure",
    budgetRange: [7, 15],
    patienceSeconds: 38,
    walkingSpeedTilesPerSecond: 2.35,
    priceSensitivity: 0.42,
    qualitySensitivity: 0.57,
    queueSensitivity: 0.94,
    distanceSensitivity: 0.72,
    noveltyPreference: 0.34,
    seatPreference: "near-stall",
    dishPreferenceTags: ["fast-service", "rice", "noodles", "filling"],
    groupSizeRange: [1, 3],
    visualRules: {
      bodyFrames: ["adult-a", "adult-b", "adult-c", "adult-d", "adult-e"],
      clothingPalettes: ["office-blue", "office-earth", "office-bright"],
      accessoryChance: 0.56,
      carryProp: "briefcase",
    },
    visitSchedule: { startHour: 11, endHour: 15, peakMultiplier: 2.1 },
    satisfactionModifiers: {
      value: 0.02,
      speed: 0.34,
      comfort: -0.04,
      variety: 0.02,
      cleanliness: 0.1,
    },
    spendMultiplier: 1.08,
    trayReturnChance: 0.7,
    unlockRequirement: { level: 1, reputation: 0, prerequisiteIds: [] },
    tags: ["lunch", "time-sensitive", "peak"],
  },
  {
    id: "customer.student-saver",
    name: "Student Saver",
    description:
      "Compares prices carefully, often arrives with friends, and will walk farther for filling food at a fair price.",
    gameplayRole: "Value and group-seating check",
    budgetRange: [4, 9],
    patienceSeconds: 66,
    walkingSpeedTilesPerSecond: 2.2,
    priceSensitivity: 0.96,
    qualitySensitivity: 0.36,
    queueSensitivity: 0.58,
    distanceSensitivity: 0.24,
    noveltyPreference: 0.48,
    seatPreference: "group-table",
    dishPreferenceTags: ["value", "filling", "noodles", "small-plate"],
    groupSizeRange: [1, 4],
    visualRules: {
      bodyFrames: ["youth-a", "youth-b", "youth-c", "youth-d"],
      clothingPalettes: ["campus-primary", "campus-pastel", "campus-neutral"],
      accessoryChance: 0.78,
      carryProp: "backpack",
    },
    visitSchedule: { startHour: 10, endHour: 20, peakMultiplier: 1.35 },
    satisfactionModifiers: {
      value: 0.34,
      speed: 0.02,
      comfort: 0.06,
      variety: 0.1,
      cleanliness: 0.02,
    },
    spendMultiplier: 0.78,
    trayReturnChance: 0.76,
    unlockRequirement: { level: 2, reputation: 8, prerequisiteIds: [] },
    tags: ["value-seeker", "social", "flexible-distance"],
  },
  {
    id: "customer.family-table",
    name: "Family Table",
    description:
      "Arrives in a larger group, waits patiently for adjacent seats, and rewards menu variety, comfort, and cleanliness.",
    gameplayRole: "Large-party seating and variety test",
    budgetRange: [18, 48],
    patienceSeconds: 95,
    walkingSpeedTilesPerSecond: 1.75,
    priceSensitivity: 0.54,
    qualitySensitivity: 0.66,
    queueSensitivity: 0.4,
    distanceSensitivity: 0.52,
    noveltyPreference: 0.5,
    seatPreference: "group-table",
    dishPreferenceTags: ["shareable", "mild", "rice", "drink", "dessert"],
    groupSizeRange: [3, 6],
    visualRules: {
      bodyFrames: ["adult-a", "adult-b", "adult-c", "child-a", "child-b"],
      clothingPalettes: ["family-jewel", "family-sun", "family-cool"],
      accessoryChance: 0.34,
      carryProp: "tote",
    },
    visitSchedule: { startHour: 10, endHour: 21, peakMultiplier: 1.25 },
    satisfactionModifiers: {
      value: 0.12,
      speed: -0.04,
      comfort: 0.24,
      variety: 0.28,
      cleanliness: 0.22,
    },
    spendMultiplier: 1.22,
    trayReturnChance: 0.64,
    unlockRequirement: { level: 3, reputation: 14, prerequisiteIds: [] },
    tags: ["group", "patient", "variety-seeker"],
  },
  {
    id: "customer.curious-food-explorer",
    name: "Curious Food Explorer",
    description:
      "Actively seeks unfamiliar dishes, tolerates a celebrated queue, and responds strongly to quality and menu breadth.",
    gameplayRole: "Novelty and reputation reward",
    budgetRange: [9, 20],
    patienceSeconds: 88,
    walkingSpeedTilesPerSecond: 1.95,
    priceSensitivity: 0.28,
    qualitySensitivity: 0.9,
    queueSensitivity: 0.3,
    distanceSensitivity: 0.18,
    noveltyPreference: 0.98,
    seatPreference: "any",
    dishPreferenceTags: ["heritage", "premium", "spicy", "seafood", "aromatic"],
    groupSizeRange: [1, 2],
    visualRules: {
      bodyFrames: ["adult-a", "adult-b", "adult-c", "adult-d", "adult-e"],
      clothingPalettes: ["explorer-coral", "explorer-teal", "explorer-mustard"],
      accessoryChance: 0.62,
      carryProp: "tote",
    },
    visitSchedule: { startHour: 11, endHour: 22, peakMultiplier: 1.18 },
    satisfactionModifiers: {
      value: -0.06,
      speed: -0.06,
      comfort: 0,
      variety: 0.36,
      cleanliness: 0.08,
    },
    spendMultiplier: 1.3,
    trayReturnChance: 0.86,
    unlockRequirement: { level: 5, reputation: 24, prerequisiteIds: [] },
    tags: ["novelty-seeker", "quality-focused", "patient"],
  },
  {
    id: "customer.senior-comfort-seeker",
    name: "Senior Comfort Seeker",
    description:
      "Moves at an unhurried pace and places extra value on short routes, accessible seating, shade, airflow, and a clean table.",
    gameplayRole: "Accessibility and comfort check",
    budgetRange: [6, 14],
    patienceSeconds: 82,
    walkingSpeedTilesPerSecond: 1.35,
    priceSensitivity: 0.63,
    qualitySensitivity: 0.61,
    queueSensitivity: 0.5,
    distanceSensitivity: 0.96,
    noveltyPreference: 0.24,
    seatPreference: "accessible",
    dishPreferenceTags: ["comfort", "soup", "soft", "mild", "coffee"],
    groupSizeRange: [1, 2],
    visualRules: {
      bodyFrames: ["senior-a", "senior-b", "senior-c", "senior-d"],
      clothingPalettes: ["senior-sage", "senior-plum", "senior-sky"],
      accessoryChance: 0.52,
      carryProp: "walking-aid",
    },
    visitSchedule: { startHour: 7, endHour: 18, peakMultiplier: 1.3 },
    satisfactionModifiers: {
      value: 0.12,
      speed: 0,
      comfort: 0.35,
      variety: -0.03,
      cleanliness: 0.28,
    },
    spendMultiplier: 0.96,
    trayReturnChance: 0.58,
    unlockRequirement: { level: 6, reputation: 30, prerequisiteIds: [] },
    tags: ["accessibility", "comfort", "off-peak"],
  },
  {
    id: "customer.evening-social-diner",
    name: "Evening Social Diner",
    description:
      "Meets friends after work, seeks breezy group seating, and lingers over shareable plates and drinks.",
    gameplayRole: "Evening dwell-time and ambience pressure",
    budgetRange: [12, 30],
    patienceSeconds: 76,
    walkingSpeedTilesPerSecond: 1.85,
    priceSensitivity: 0.38,
    qualitySensitivity: 0.7,
    queueSensitivity: 0.46,
    distanceSensitivity: 0.3,
    noveltyPreference: 0.62,
    seatPreference: "breezy",
    dishPreferenceTags: ["shareable", "seafood", "small-plate", "drink", "dessert"],
    groupSizeRange: [2, 5],
    visualRules: {
      bodyFrames: ["adult-a", "adult-b", "adult-c", "adult-d", "adult-e"],
      clothingPalettes: ["evening-indigo", "evening-rust", "evening-mint"],
      accessoryChance: 0.46,
      carryProp: "none",
    },
    visitSchedule: { startHour: 17, endHour: 23, peakMultiplier: 1.8 },
    satisfactionModifiers: {
      value: 0,
      speed: -0.08,
      comfort: 0.22,
      variety: 0.2,
      cleanliness: 0.12,
    },
    spendMultiplier: 1.34,
    trayReturnChance: 0.74,
    unlockRequirement: { level: 8, reputation: 40, prerequisiteIds: [] },
    tags: ["evening", "group", "long-dwell"],
  },
  {
    id: "customer.quality-treat-seeker",
    name: "Quality Treat Seeker",
    description:
      "Visits less often but spends freely on excellent signature dishes, polished surroundings, and attentive service.",
    gameplayRole: "Late-game quality and ambience reward",
    budgetRange: [18, 42],
    patienceSeconds: 70,
    walkingSpeedTilesPerSecond: 1.9,
    priceSensitivity: 0.08,
    qualitySensitivity: 0.99,
    queueSensitivity: 0.56,
    distanceSensitivity: 0.34,
    noveltyPreference: 0.76,
    seatPreference: "quiet",
    dishPreferenceTags: ["premium", "heritage", "seafood", "braised", "dessert"],
    groupSizeRange: [1, 3],
    visualRules: {
      bodyFrames: ["adult-a", "adult-b", "adult-c", "adult-d", "adult-e"],
      clothingPalettes: ["treat-charcoal", "treat-jade", "treat-cream"],
      accessoryChance: 0.64,
      carryProp: "none",
    },
    visitSchedule: { startHour: 12, endHour: 22, peakMultiplier: 1.12 },
    satisfactionModifiers: {
      value: -0.18,
      speed: 0.04,
      comfort: 0.18,
      variety: 0.16,
      cleanliness: 0.25,
    },
    spendMultiplier: 1.65,
    trayReturnChance: 0.9,
    unlockRequirement: { level: 11, reputation: 56, prerequisiteIds: [] },
    tags: ["premium", "quality-focused", "ambience-focused"],
  },
] as const satisfies readonly CustomerSeed[];

export const CUSTOMER_ARCHETYPES: readonly CustomerArchetypeDefinition[] =
  customerSeeds.map(
    ({ name, description, ...customer }) => {
      void name;
      void description;
      return {
        ...customer,
        nameKey: `customer.${customer.id.slice("customer.".length)}.name`,
        descriptionKey: `customer.${customer.id.slice("customer.".length)}.description`,
      };
    },
  );

export const CUSTOMER_ENGLISH: Readonly<Record<string, string>> =
  Object.fromEntries(
    customerSeeds.flatMap((customer) => [
      [`customer.${customer.id.slice("customer.".length)}.name`, customer.name],
      [
        `customer.${customer.id.slice("customer.".length)}.description`,
        customer.description,
      ],
    ]),
  );
