import type {
  DietaryTag,
  DishCategory,
  DishDefinition,
  LocalizedSeed,
} from "./types";

interface DishInput extends LocalizedSeed {
  readonly id: `dish.${string}`;
  readonly stallId: `stall.${string}`;
  readonly category: DishCategory;
  readonly price: number;
  readonly demand: number;
  readonly preparationSeconds: number;
  readonly eatingSeconds: number;
  readonly quality: number;
  readonly preferenceTags: readonly string[];
  readonly dietaryTags: readonly DietaryTag[];
  readonly level: number;
  readonly reputation: number;
  readonly container: "plate" | "bowl" | "cup" | "glass" | "leaf-lined-plate" | "platter";
  readonly colour: string;
  readonly steam: "none" | "light" | "full";
}

type DishSeed = Omit<DishDefinition, "nameKey" | "descriptionKey"> &
  LocalizedSeed;

const dishInputs = [
  {
    id: "dish.poached-chicken-rice",
    stallId: "stall.sunrise-roost",
    name: "Poached Chicken Rice",
    description:
      "Tender poached chicken with fragrant rice, cucumber, clear broth, and separate chilli and dark soy condiments.",
    category: "rice",
    price: 7,
    demand: 0.86,
    preparationSeconds: 24,
    eatingSeconds: 44,
    quality: 0.72,
    preferenceTags: ["comfort", "chicken", "rice", "mild"],
    dietaryTags: [],
    level: 1,
    reputation: 0,
    container: "plate",
    colour: "#E8D6B3",
    steam: "light",
  },
  {
    id: "dish.roast-chicken-rice",
    stallId: "stall.sunrise-roost",
    name: "Roast Chicken Rice",
    description:
      "Roast chicken with crisp-edged skin, aromatic rice, cucumber, broth, and condiments served separately.",
    category: "rice",
    price: 8,
    demand: 0.82,
    preparationSeconds: 28,
    eatingSeconds: 46,
    quality: 0.75,
    preferenceTags: ["roasted", "chicken", "rice", "savoury"],
    dietaryTags: [],
    level: 2,
    reputation: 10,
    container: "plate",
    colour: "#B66A3C",
    steam: "light",
  },
  {
    id: "dish.soya-tofu-rice",
    stallId: "stall.sunrise-roost",
    name: "Soya Tofu Rice",
    description:
      "Braised tofu and mushrooms over fragrant rice with cucumber and a light soy dressing; this stall's meat-free recipe.",
    category: "rice",
    price: 6,
    demand: 0.61,
    preparationSeconds: 22,
    eatingSeconds: 42,
    quality: 0.7,
    preferenceTags: ["tofu", "rice", "mild", "vegetable-forward"],
    dietaryTags: ["plant-based-recipe"],
    level: 3,
    reputation: 15,
    container: "plate",
    colour: "#C8A96A",
    steam: "light",
  },
  {
    id: "dish.chicken-congee",
    stallId: "stall.sunrise-roost",
    name: "Chicken Congee",
    description:
      "Silky rice porridge topped with sliced chicken, spring onion, ginger, and a dash of sesame oil.",
    category: "rice",
    price: 6,
    demand: 0.66,
    preparationSeconds: 20,
    eatingSeconds: 50,
    quality: 0.73,
    preferenceTags: ["comfort", "breakfast", "chicken", "soft"],
    dietaryTags: [],
    level: 4,
    reputation: 20,
    container: "bowl",
    colour: "#F4EBD0",
    steam: "full",
  },
  {
    id: "dish.nasi-lemak",
    stallId: "stall.coconut-lime",
    name: "Nasi Lemak",
    description:
      "Coconut rice with sambal, cucumber, peanuts, fried anchovies, egg, and a crisp chicken wing in this house set.",
    category: "rice",
    price: 8,
    demand: 0.88,
    preparationSeconds: 30,
    eatingSeconds: 48,
    quality: 0.76,
    preferenceTags: ["coconut", "rice", "spicy", "crisp"],
    dietaryTags: ["contains-egg", "contains-peanuts", "contains-seafood", "spicy"],
    level: 1,
    reputation: 0,
    container: "leaf-lined-plate",
    colour: "#E8E0B5",
    steam: "light",
  },
  {
    id: "dish.mee-rebus",
    stallId: "stall.coconut-lime",
    name: "Mee Rebus",
    description:
      "Yellow noodles in a thick, gently spiced sweet-potato gravy with tofu, beansprouts, egg, lime, and fried shallots.",
    category: "noodles",
    price: 7,
    demand: 0.74,
    preparationSeconds: 32,
    eatingSeconds: 54,
    quality: 0.74,
    preferenceTags: ["noodles", "gravy", "sweet-savoury", "comfort"],
    dietaryTags: ["contains-egg", "spicy"],
    level: 2,
    reputation: 10,
    container: "bowl",
    colour: "#C88732",
    steam: "full",
  },
  {
    id: "dish.soto-ayam",
    stallId: "stall.coconut-lime",
    name: "Soto Ayam",
    description:
      "Aromatic turmeric chicken soup with rice cakes, shredded chicken, beansprouts, herbs, and fried shallots.",
    category: "soup",
    price: 7,
    demand: 0.69,
    preparationSeconds: 29,
    eatingSeconds: 55,
    quality: 0.76,
    preferenceTags: ["soup", "chicken", "aromatic", "comfort"],
    dietaryTags: [],
    level: 3,
    reputation: 17,
    container: "bowl",
    colour: "#E5B94B",
    steam: "full",
  },
  {
    id: "dish.lontong-sayur",
    stallId: "stall.coconut-lime",
    name: "Lontong Sayur",
    description:
      "Compressed rice cakes, cabbage, long beans, and tofu in a gently spiced coconut vegetable gravy.",
    category: "soup",
    price: 7,
    demand: 0.65,
    preparationSeconds: 31,
    eatingSeconds: 52,
    quality: 0.75,
    preferenceTags: ["coconut", "vegetable-forward", "rice-cake", "gravy"],
    dietaryTags: ["plant-based-recipe", "spicy"],
    level: 4,
    reputation: 22,
    container: "bowl",
    colour: "#D9A85E",
    steam: "full",
  },
  {
    id: "dish.kopi",
    stallId: "stall.kopi-canopy",
    name: "Kopi",
    description:
      "Robust local-style coffee brewed through a cloth filter and rounded with sweetened condensed milk.",
    category: "drink",
    price: 3,
    demand: 0.82,
    preparationSeconds: 15,
    eatingSeconds: 34,
    quality: 0.68,
    preferenceTags: ["coffee", "sweet", "breakfast", "drink"],
    dietaryTags: ["contains-dairy"],
    level: 2,
    reputation: 10,
    container: "cup",
    colour: "#835A3B",
    steam: "full",
  },
  {
    id: "dish.sugarcane-juice",
    stallId: "stall.kopi-canopy",
    name: "Fresh Sugarcane Juice",
    description:
      "Chilled sugarcane juice pressed to order and served over ice with an optional squeeze of calamansi.",
    category: "drink",
    price: 4,
    demand: 0.72,
    preparationSeconds: 18,
    eatingSeconds: 31,
    quality: 0.7,
    preferenceTags: ["cold", "refreshing", "sweet", "drink"],
    dietaryTags: ["plant-based-recipe"],
    level: 3,
    reputation: 16,
    container: "glass",
    colour: "#C9D36D",
    steam: "none",
  },
  {
    id: "dish.ice-kacang",
    stallId: "stall.kopi-canopy",
    name: "Ice Kacang",
    description:
      "A mound of shaved ice with colourful syrups, sweet corn, red beans, grass jelly, and evaporated milk.",
    category: "dessert",
    price: 6,
    demand: 0.77,
    preparationSeconds: 25,
    eatingSeconds: 46,
    quality: 0.73,
    preferenceTags: ["dessert", "cold", "sweet", "colourful"],
    dietaryTags: ["contains-dairy"],
    level: 5,
    reputation: 25,
    container: "bowl",
    colour: "#E66DA5",
    steam: "none",
  },
  {
    id: "dish.char-kway-teow",
    stallId: "stall.cinder-wok",
    name: "Char Kway Teow",
    description:
      "Flat rice noodles wok-fried with dark soy, egg, beansprouts, chives, fish cake, and prawns in this stall's recipe.",
    category: "noodles",
    price: 9,
    demand: 0.9,
    preparationSeconds: 42,
    eatingSeconds: 52,
    quality: 0.8,
    preferenceTags: ["wok", "noodles", "smoky", "seafood"],
    dietaryTags: ["contains-egg", "contains-seafood"],
    level: 3,
    reputation: 16,
    container: "plate",
    colour: "#70452D",
    steam: "full",
  },
  {
    id: "dish.hokkien-prawn-mee",
    stallId: "stall.cinder-wok",
    name: "Hokkien Prawn Mee",
    description:
      "Yellow noodles and thick rice vermicelli simmered in prawn stock with prawns, squid, egg, chives, lime, and sambal.",
    category: "noodles",
    price: 10,
    demand: 0.85,
    preparationSeconds: 45,
    eatingSeconds: 55,
    quality: 0.82,
    preferenceTags: ["seafood", "noodles", "stock-rich", "wok"],
    dietaryTags: ["contains-egg", "contains-seafood", "spicy"],
    level: 4,
    reputation: 21,
    container: "plate",
    colour: "#C58D3E",
    steam: "full",
  },
  {
    id: "dish.fried-carrot-cake",
    stallId: "stall.cinder-wok",
    name: "Fried Carrot Cake",
    description:
      "Steamed radish cake cubes fried with egg, preserved radish, garlic, and spring onion in the savoury white style.",
    category: "small-plate",
    price: 7,
    demand: 0.76,
    preparationSeconds: 38,
    eatingSeconds: 43,
    quality: 0.76,
    preferenceTags: ["griddle", "egg", "savoury", "shareable"],
    dietaryTags: ["contains-egg"],
    level: 5,
    reputation: 27,
    container: "plate",
    colour: "#E8D9B2",
    steam: "light",
  },
  {
    id: "dish.oyster-omelette",
    stallId: "stall.cinder-wok",
    name: "Oyster Omelette",
    description:
      "A crisp-chewy egg and starch batter scattered with oysters and coriander, served with a tangy chilli dip.",
    category: "small-plate",
    price: 11,
    demand: 0.73,
    preparationSeconds: 46,
    eatingSeconds: 49,
    quality: 0.83,
    preferenceTags: ["seafood", "egg", "crisp", "shareable"],
    dietaryTags: ["contains-egg", "contains-seafood", "spicy"],
    level: 6,
    reputation: 31,
    container: "plate",
    colour: "#D8A94A",
    steam: "light",
  },
  {
    id: "dish.roti-prata",
    stallId: "stall.tiffin-lantern",
    name: "Roti Prata Set",
    description:
      "Flaky griddled flatbread served torn or folded with separate dhal and fish curry for dipping.",
    category: "bread",
    price: 6,
    demand: 0.86,
    preparationSeconds: 36,
    eatingSeconds: 45,
    quality: 0.78,
    preferenceTags: ["bread", "griddle", "curry", "value"],
    dietaryTags: ["contains-dairy", "contains-seafood", "spicy"],
    level: 5,
    reputation: 24,
    container: "plate",
    colour: "#D8A85A",
    steam: "light",
  },
  {
    id: "dish.mee-goreng-mamak",
    stallId: "stall.tiffin-lantern",
    name: "Mee Goreng Mamak",
    description:
      "Yellow noodles stir-fried with tofu, potato, greens, tomato, egg, and a sweet-spicy sauce, finished with lime.",
    category: "noodles",
    price: 8,
    demand: 0.8,
    preparationSeconds: 41,
    eatingSeconds: 50,
    quality: 0.79,
    preferenceTags: ["noodles", "wok", "sweet-spicy", "filling"],
    dietaryTags: ["contains-egg", "spicy"],
    level: 6,
    reputation: 30,
    container: "plate",
    colour: "#D05C35",
    steam: "full",
  },
  {
    id: "dish.chicken-murtabak",
    stallId: "stall.tiffin-lantern",
    name: "Chicken Murtabak",
    description:
      "A substantial griddled parcel filled with spiced minced chicken, onion, and egg, served with curry.",
    category: "bread",
    price: 11,
    demand: 0.76,
    preparationSeconds: 48,
    eatingSeconds: 57,
    quality: 0.82,
    preferenceTags: ["bread", "chicken", "shareable", "filling"],
    dietaryTags: ["contains-egg", "spicy"],
    level: 7,
    reputation: 35,
    container: "platter",
    colour: "#B77B37",
    steam: "light",
  },
  {
    id: "dish.nasi-briyani",
    stallId: "stall.tiffin-lantern",
    name: "Chicken Nasi Briyani",
    description:
      "Long-grain spiced rice with tender chicken, achar, and a small bowl of curry gravy served alongside.",
    category: "rice",
    price: 12,
    demand: 0.82,
    preparationSeconds: 43,
    eatingSeconds: 59,
    quality: 0.84,
    preferenceTags: ["rice", "chicken", "aromatic", "filling"],
    dietaryTags: ["spicy"],
    level: 8,
    reputation: 40,
    container: "plate",
    colour: "#E0A43A",
    steam: "full",
  },
  {
    id: "dish.masala-thosai",
    stallId: "stall.tamarind-leaf",
    name: "Masala Thosai",
    description:
      "A crisp fermented rice-and-lentil crepe wrapped around spiced potato and served with sambar and chutneys.",
    category: "bread",
    price: 8,
    demand: 0.82,
    preparationSeconds: 39,
    eatingSeconds: 50,
    quality: 0.82,
    preferenceTags: ["crisp", "lentil", "potato", "vegetarian-menu"],
    dietaryTags: ["plant-based-recipe", "spicy"],
    level: 7,
    reputation: 34,
    container: "leaf-lined-plate",
    colour: "#D7A34C",
    steam: "light",
  },
  {
    id: "dish.idli-sambar",
    stallId: "stall.tamarind-leaf",
    name: "Idli Sambar",
    description:
      "Steamed rice-and-lentil cakes with lentil-vegetable sambar and two house chutneys.",
    category: "small-plate",
    price: 6,
    demand: 0.67,
    preparationSeconds: 26,
    eatingSeconds: 44,
    quality: 0.79,
    preferenceTags: ["soft", "lentil", "breakfast", "vegetarian-menu"],
    dietaryTags: ["plant-based-recipe", "spicy"],
    level: 8,
    reputation: 39,
    container: "leaf-lined-plate",
    colour: "#EEE6CD",
    steam: "full",
  },
  {
    id: "dish.vadai-set",
    stallId: "stall.tamarind-leaf",
    name: "Vadai Set",
    description:
      "Crisp savoury lentil fritters with sambar and coconut chutney, plated as a light meal or shared snack.",
    category: "small-plate",
    price: 6,
    demand: 0.64,
    preparationSeconds: 31,
    eatingSeconds: 38,
    quality: 0.78,
    preferenceTags: ["crisp", "lentil", "snack", "vegetarian-menu"],
    dietaryTags: ["plant-based-recipe", "spicy"],
    level: 9,
    reputation: 45,
    container: "leaf-lined-plate",
    colour: "#A96A32",
    steam: "light",
  },
  {
    id: "dish.lemon-rice",
    stallId: "stall.tamarind-leaf",
    name: "Lemon Rice Set",
    description:
      "Turmeric rice brightened with lemon, mustard seed, curry leaves, and peanuts, served with vegetable sides.",
    category: "rice",
    price: 7,
    demand: 0.69,
    preparationSeconds: 28,
    eatingSeconds: 45,
    quality: 0.8,
    preferenceTags: ["rice", "citrus", "aromatic", "vegetarian-menu"],
    dietaryTags: ["contains-peanuts", "plant-based-recipe", "spicy"],
    level: 10,
    reputation: 50,
    container: "leaf-lined-plate",
    colour: "#E1BF3B",
    steam: "light",
  },
  {
    id: "dish.nyonya-laksa",
    stallId: "stall.straits-hearth",
    name: "Nyonya Laksa",
    description:
      "Thick rice noodles in a fragrant coconut-spice broth with prawns, fish cake, tofu puff, and herbs.",
    category: "noodles",
    price: 11,
    demand: 0.87,
    preparationSeconds: 43,
    eatingSeconds: 57,
    quality: 0.88,
    preferenceTags: ["coconut", "noodles", "seafood", "spicy"],
    dietaryTags: ["contains-seafood", "spicy"],
    level: 9,
    reputation: 46,
    container: "bowl",
    colour: "#D56B3D",
    steam: "full",
  },
  {
    id: "dish.ayam-buah-keluak",
    stallId: "stall.straits-hearth",
    name: "Ayam Buah Keluak",
    description:
      "Chicken slowly braised in a dark, earthy buah keluak gravy, served with rice in a carefully prepared house portion.",
    category: "rice",
    price: 14,
    demand: 0.68,
    preparationSeconds: 52,
    eatingSeconds: 62,
    quality: 0.91,
    preferenceTags: ["braised", "chicken", "earthy", "heritage"],
    dietaryTags: ["spicy"],
    level: 10,
    reputation: 52,
    container: "plate",
    colour: "#513C2C",
    steam: "full",
  },
  {
    id: "dish.chap-chye",
    stallId: "stall.straits-hearth",
    name: "Chap Chye with Rice",
    description:
      "Cabbage, mushrooms, tofu skin, and glass noodles slowly braised in a savoury bean-paste gravy, served with rice.",
    category: "rice",
    price: 9,
    demand: 0.63,
    preparationSeconds: 38,
    eatingSeconds: 51,
    quality: 0.84,
    preferenceTags: ["braised", "vegetable-forward", "comfort", "rice"],
    dietaryTags: ["plant-based-recipe"],
    level: 11,
    reputation: 57,
    container: "plate",
    colour: "#8A7650",
    steam: "full",
  },
  {
    id: "dish.babi-pongteh",
    stallId: "stall.straits-hearth",
    name: "Babi Pongteh",
    description:
      "Pork and potato braised until tender in a mellow fermented-soybean gravy, served with steamed rice.",
    category: "rice",
    price: 13,
    demand: 0.7,
    preparationSeconds: 48,
    eatingSeconds: 60,
    quality: 0.89,
    preferenceTags: ["pork", "braised", "sweet-savoury", "rice"],
    dietaryTags: ["contains-pork"],
    level: 12,
    reputation: 62,
    container: "plate",
    colour: "#98603E",
    steam: "full",
  },
  {
    id: "dish.sambal-stingray",
    stallId: "stall.harbour-ember",
    name: "Sambal Stingray",
    description:
      "Stingray grilled on a leaf lining with a robust sambal, served with onion, cucumber, and calamansi.",
    category: "seafood",
    price: 16,
    demand: 0.84,
    preparationSeconds: 55,
    eatingSeconds: 64,
    quality: 0.92,
    preferenceTags: ["seafood", "grilled", "spicy", "shareable"],
    dietaryTags: ["contains-seafood", "spicy"],
    level: 12,
    reputation: 62,
    container: "leaf-lined-plate",
    colour: "#B64836",
    steam: "full",
  },
  {
    id: "dish.sliced-fish-soup",
    stallId: "stall.harbour-ember",
    name: "Sliced Fish Soup",
    description:
      "Fresh fish slices, leafy greens, tofu, tomato, and rice vermicelli in a clear, gently savoury broth.",
    category: "soup",
    price: 10,
    demand: 0.75,
    preparationSeconds: 40,
    eatingSeconds: 58,
    quality: 0.87,
    preferenceTags: ["seafood", "soup", "light", "comfort"],
    dietaryTags: ["contains-seafood"],
    level: 13,
    reputation: 68,
    container: "bowl",
    colour: "#D9D5B8",
    steam: "full",
  },
  {
    id: "dish.black-pepper-crab",
    stallId: "stall.harbour-ember",
    name: "Black Pepper Crab",
    description:
      "Crab wok-tossed in a glossy black-pepper sauce and served as a premium shared platter with toasted buns.",
    category: "seafood",
    price: 24,
    demand: 0.72,
    preparationSeconds: 65,
    eatingSeconds: 72,
    quality: 0.95,
    preferenceTags: ["seafood", "peppery", "premium", "shareable"],
    dietaryTags: ["contains-seafood", "spicy"],
    level: 14,
    reputation: 74,
    container: "platter",
    colour: "#A53D2D",
    steam: "full",
  },
  {
    id: "dish.bak-chor-mee",
    stallId: "stall.mee-pok-junction",
    name: "Bak Chor Mee",
    description:
      "Springy mee pok tossed with black vinegar, chilli, and pork lard, topped with minced pork, mushrooms, fish cake, and a side of soup.",
    category: "noodles",
    price: 8,
    demand: 0.88,
    preparationSeconds: 34,
    eatingSeconds: 51,
    quality: 0.8,
    preferenceTags: ["vinegar", "noodles", "pork", "umami"],
    dietaryTags: ["contains-pork", "contains-seafood", "spicy"],
    level: 4,
    reputation: 20,
    container: "bowl",
    colour: "#B86E3D",
    steam: "full",
  },
  {
    id: "dish.fishball-mee-pok",
    stallId: "stall.mee-pok-junction",
    name: "Fishball Mee Pok",
    description:
      "Flat mee pok with springy fishballs, fish cake, beansprouts, and spring onion, dressed lightly and paired with clear soup.",
    category: "noodles",
    price: 7,
    demand: 0.79,
    preparationSeconds: 31,
    eatingSeconds: 48,
    quality: 0.76,
    preferenceTags: ["seafood", "noodles", "springy", "light"],
    dietaryTags: ["contains-seafood"],
    level: 5,
    reputation: 25,
    container: "bowl",
    colour: "#E5B15E",
    steam: "light",
  },
  {
    id: "dish.lor-mee",
    stallId: "stall.mee-pok-junction",
    name: "Lor Mee",
    description:
      "Thick yellow noodles under a glossy dark gravy with braised pork, egg, fish cake, beansprouts, garlic, and black vinegar.",
    category: "noodles",
    price: 9,
    demand: 0.76,
    preparationSeconds: 38,
    eatingSeconds: 54,
    quality: 0.79,
    preferenceTags: ["gravy", "noodles", "braised", "comfort"],
    dietaryTags: ["contains-egg", "contains-pork", "contains-seafood"],
    level: 6,
    reputation: 31,
    container: "bowl",
    colour: "#8C5A34",
    steam: "full",
  },
  {
    id: "dish.teochew-fish-dumpling-soup",
    stallId: "stall.mee-pok-junction",
    name: "Teochew Fish Dumpling Soup",
    description:
      "Handmade fish-paste dumplings filled with seasoned pork, served in a clear broth with lettuce, fishballs, and fried shallot.",
    category: "soup",
    price: 9,
    demand: 0.7,
    preparationSeconds: 34,
    eatingSeconds: 55,
    quality: 0.82,
    preferenceTags: ["soup", "seafood", "light", "handmade"],
    dietaryTags: ["contains-pork", "contains-seafood"],
    level: 7,
    reputation: 36,
    container: "bowl",
    colour: "#D7CEA4",
    steam: "full",
  },
  {
    id: "dish.chendol",
    stallId: "stall.sweet-monsoon",
    name: "Chendol",
    description:
      "Shaved ice layered with pandan jelly, red beans, coconut milk, and a dark gula melaka syrup that pools through the bowl.",
    category: "dessert",
    price: 6,
    demand: 0.84,
    preparationSeconds: 23,
    eatingSeconds: 44,
    quality: 0.76,
    preferenceTags: ["dessert", "coconut", "cold", "pandan"],
    dietaryTags: ["plant-based-recipe"],
    level: 5,
    reputation: 25,
    container: "bowl",
    colour: "#63A84E",
    steam: "none",
  },
  {
    id: "dish.tau-huay",
    stallId: "stall.sweet-monsoon",
    name: "Tau Huay",
    description:
      "Silken soy pudding spooned into a bowl with light ginger syrup, its soft ivory curds served gently warm.",
    category: "dessert",
    price: 4,
    demand: 0.68,
    preparationSeconds: 17,
    eatingSeconds: 36,
    quality: 0.73,
    preferenceTags: ["soy", "silky", "light", "dessert"],
    dietaryTags: ["plant-based-recipe"],
    level: 6,
    reputation: 30,
    container: "bowl",
    colour: "#F4E7C6",
    steam: "light",
  },
  {
    id: "dish.teh-tarik",
    stallId: "stall.sweet-monsoon",
    name: "Teh Tarik",
    description:
      "Strong black tea and condensed milk pulled between metal mugs until smooth, aromatic, and crowned with a fine foam.",
    category: "drink",
    price: 4,
    demand: 0.78,
    preparationSeconds: 20,
    eatingSeconds: 32,
    quality: 0.75,
    preferenceTags: ["tea", "frothy", "sweet", "drink"],
    dietaryTags: ["contains-dairy"],
    level: 7,
    reputation: 36,
    container: "glass",
    colour: "#C88345",
    steam: "full",
  },
  {
    id: "dish.pulut-hitam",
    stallId: "stall.sweet-monsoon",
    name: "Pulut Hitam",
    description:
      "Black glutinous rice simmered into a nutty purple porridge and finished with a bright ribbon of coconut cream.",
    category: "dessert",
    price: 6,
    demand: 0.7,
    preparationSeconds: 26,
    eatingSeconds: 45,
    quality: 0.78,
    preferenceTags: ["glutinous-rice", "coconut", "warm", "dessert"],
    dietaryTags: ["plant-based-recipe"],
    level: 8,
    reputation: 42,
    container: "bowl",
    colour: "#4B344F",
    steam: "full",
  },
  {
    id: "dish.chicken-satay-set",
    stallId: "stall.satay-meridian",
    name: "Chicken Satay Set",
    description:
      "Charcoal-grilled chicken skewers with smoky caramelised edges, served with peanut sauce, cucumber, onion, and pressed rice cake.",
    category: "small-plate",
    price: 10,
    demand: 0.86,
    preparationSeconds: 42,
    eatingSeconds: 48,
    quality: 0.8,
    preferenceTags: ["chicken", "skewers", "grilled", "shareable"],
    dietaryTags: ["contains-peanuts"],
    level: 6,
    reputation: 31,
    container: "platter",
    colour: "#BB6A32",
    steam: "light",
  },
  {
    id: "dish.bbq-chicken-wings",
    stallId: "stall.satay-meridian",
    name: "Barbecued Chicken Wings",
    description:
      "Whole chicken wings lacquered over charcoal until bronze and sticky, with cucumber and a sharp calamansi chilli dip.",
    category: "small-plate",
    price: 9,
    demand: 0.8,
    preparationSeconds: 45,
    eatingSeconds: 50,
    quality: 0.79,
    preferenceTags: ["chicken", "charcoal", "sticky", "shareable"],
    dietaryTags: ["spicy"],
    level: 7,
    reputation: 36,
    container: "platter",
    colour: "#9E3F2F",
    steam: "full",
  },
  {
    id: "dish.beef-satay-set",
    stallId: "stall.satay-meridian",
    name: "Beef Satay Set",
    description:
      "Tender beef skewers marinated with lemongrass and warm spices, grilled over charcoal and plated with peanut sauce and ketupat.",
    category: "small-plate",
    price: 12,
    demand: 0.75,
    preparationSeconds: 47,
    eatingSeconds: 52,
    quality: 0.83,
    preferenceTags: ["beef", "skewers", "grilled", "premium"],
    dietaryTags: ["contains-peanuts"],
    level: 8,
    reputation: 41,
    container: "platter",
    colour: "#74402C",
    steam: "light",
  },
  {
    id: "dish.sambal-grilled-squid",
    stallId: "stall.satay-meridian",
    name: "Sambal Grilled Squid",
    description:
      "Scored squid grilled until lightly charred, brushed with brick-red sambal, and finished with onion, cucumber, and calamansi.",
    category: "seafood",
    price: 15,
    demand: 0.78,
    preparationSeconds: 50,
    eatingSeconds: 57,
    quality: 0.85,
    preferenceTags: ["seafood", "grilled", "spicy", "shareable"],
    dietaryTags: ["contains-seafood", "spicy"],
    level: 9,
    reputation: 47,
    container: "leaf-lined-plate",
    colour: "#C54B35",
    steam: "full",
  },
  {
    id: "dish.har-gow",
    stallId: "stall.bamboo-basket",
    name: "Har Gow",
    description:
      "Translucent pleated dumplings wrapped around juicy prawn filling, steamed in a bamboo basket and served in a set of four.",
    category: "small-plate",
    price: 8,
    demand: 0.8,
    preparationSeconds: 29,
    eatingSeconds: 38,
    quality: 0.83,
    preferenceTags: ["seafood", "dim-sum", "steamed", "delicate"],
    dietaryTags: ["contains-seafood"],
    level: 8,
    reputation: 41,
    container: "platter",
    colour: "#E9DDD2",
    steam: "full",
  },
  {
    id: "dish.siew-mai",
    stallId: "stall.bamboo-basket",
    name: "Siew Mai",
    description:
      "Open-topped yellow dumplings packed with seasoned pork and prawn, each crowned with carrot and steamed until glossy.",
    category: "small-plate",
    price: 8,
    demand: 0.82,
    preparationSeconds: 30,
    eatingSeconds: 39,
    quality: 0.82,
    preferenceTags: ["pork", "dim-sum", "steamed", "savoury"],
    dietaryTags: ["contains-pork", "contains-seafood"],
    level: 9,
    reputation: 46,
    container: "platter",
    colour: "#E1AE46",
    steam: "full",
  },
  {
    id: "dish.char-siew-bao",
    stallId: "stall.bamboo-basket",
    name: "Char Siew Bao",
    description:
      "Fluffy white steamed buns split to reveal a glossy sweet-savoury char siew pork filling, served three to a basket.",
    category: "bread",
    price: 7,
    demand: 0.76,
    preparationSeconds: 31,
    eatingSeconds: 40,
    quality: 0.81,
    preferenceTags: ["pork", "dim-sum", "steamed-bun", "sweet-savoury"],
    dietaryTags: ["contains-pork"],
    level: 10,
    reputation: 51,
    container: "platter",
    colour: "#F2E4CF",
    steam: "full",
  },
  {
    id: "dish.lotus-leaf-rice",
    stallId: "stall.bamboo-basket",
    name: "Lotus Leaf Rice",
    description:
      "Glutinous rice steamed inside a lotus leaf with chicken, mushroom, dried shrimp, and Chinese sausage until deeply aromatic.",
    category: "rice",
    price: 10,
    demand: 0.74,
    preparationSeconds: 40,
    eatingSeconds: 52,
    quality: 0.85,
    preferenceTags: ["glutinous-rice", "chicken", "aromatic", "dim-sum"],
    dietaryTags: ["contains-pork", "contains-seafood"],
    level: 11,
    reputation: 56,
    container: "leaf-lined-plate",
    colour: "#75633B",
    steam: "full",
  },
] as const satisfies readonly DishInput[];

const dishSeeds: readonly DishSeed[] = dishInputs.map((dish) => ({
  id: dish.id,
  name: dish.name,
  description: dish.description,
  stallIds: [dish.stallId],
  category: dish.category,
  price: dish.price,
  baseDemand: dish.demand,
  preparationTimeMs: dish.preparationSeconds * 1_000,
  servingTimeMs: Math.max(1_200, Math.round(dish.preparationSeconds * 70)),
  eatingTimeMs: dish.eatingSeconds * 1_000,
  quality: dish.quality,
  preferenceTags: dish.preferenceTags,
  dietaryTags: dish.dietaryTags,
  unlockRequirement: {
    level: dish.level,
    reputation: dish.reputation,
    prerequisiteIds: [dish.stallId],
  },
  foodSprite: { atlas: "food", frame: dish.id.slice("dish.".length) },
  containerSprite: { atlas: "serviceware", frame: dish.container },
  portionColour: dish.colour,
  steamEffect: dish.steam,
}));

export const DISHES: readonly DishDefinition[] = dishSeeds.map(
  ({ name, description, ...dish }) => {
    void name;
    void description;
    return {
      ...dish,
      nameKey: `dish.${dish.id.slice("dish.".length)}.name`,
      descriptionKey: `dish.${dish.id.slice("dish.".length)}.description`,
    };
  },
);

export const DISH_ENGLISH: Readonly<Record<string, string>> = Object.fromEntries(
  dishSeeds.flatMap((dish) => [
    [`dish.${dish.id.slice("dish.".length)}.name`, dish.name],
    [`dish.${dish.id.slice("dish.".length)}.description`, dish.description],
  ]),
);
