import type {
  AudioReference,
  GridPoint,
  InteractionPoint,
  LocalizedSeed,
  PlaceableCategory,
  PlaceableDefinition,
  Rotation,
  SeatPoint,
} from "./types";

interface PlaceableInput extends LocalizedSeed {
  readonly id: `item.${string}`;
  readonly category: PlaceableCategory;
  readonly footprint: { readonly width: number; readonly height: number };
  readonly price: number;
  readonly level: number;
  readonly reputation: number;
  readonly ambience: number;
  readonly cleanliness: number;
  readonly tags: readonly string[];
  readonly rotations?: readonly Rotation[];
  readonly walkability?: PlaceableDefinition["walkability"];
  readonly interactions?: readonly InteractionPoint[];
  readonly seats?: readonly SeatPoint[];
  readonly queuePoints?: readonly GridPoint[];
  readonly animations?: readonly string[];
  readonly audio?: readonly AudioReference[];
  readonly upkeep?: number;
  readonly lightRadius?: number;
  readonly service?: Partial<PlaceableDefinition["serviceModifiers"]>;
  readonly prerequisiteIds?: readonly string[];
}

const placeableInputs = [
  // Tables: 8. Each changes capacity, footprint, accessibility, or dwell quality.
  {
    id: "item.compact-square-table",
    name: "Compact Square Table",
    description: "A space-efficient two-person laminate table suited to tight starter layouts.",
    category: "table",
    footprint: { width: 1, height: 1 },
    price: 90,
    level: 1,
    reputation: 0,
    ambience: 1,
    cleanliness: 0,
    tags: ["two-seat-layout", "starter", "laminate"],
  },
  {
    id: "item.round-cafe-table",
    name: "Round Café Table",
    description: "A round table that keeps corners out of busy aisles and supports flexible chair placement.",
    category: "table",
    footprint: { width: 2, height: 2 },
    price: 190,
    level: 2,
    reputation: 10,
    ambience: 3,
    cleanliness: 0,
    tags: ["four-seat-layout", "rounded-edge", "social"],
  },
  {
    id: "item.long-communal-table",
    name: "Long Communal Table",
    description: "A durable long table that efficiently serves mixed groups in classic communal seating rows.",
    category: "table",
    footprint: { width: 4, height: 1 },
    price: 330,
    level: 3,
    reputation: 16,
    ambience: 4,
    cleanliness: 0,
    tags: ["eight-seat-layout", "communal", "high-capacity"],
  },
  {
    id: "item.family-trestle-table",
    name: "Family Trestle Table",
    description: "A broad, stable table with generous room for shared plates and larger groups.",
    category: "table",
    footprint: { width: 3, height: 2 },
    price: 420,
    level: 5,
    reputation: 24,
    ambience: 6,
    cleanliness: 0,
    tags: ["family", "shared-dishes", "six-seat-layout"],
    service: { eatingSpeed: 0.03 },
  },
  {
    id: "item.accessible-end-table",
    name: "Accessible End Table",
    description: "A height-considered table with clear knee space and a marked wheelchair approach at one end.",
    category: "table",
    footprint: { width: 2, height: 1 },
    price: 240,
    level: 3,
    reputation: 18,
    ambience: 4,
    cleanliness: 0,
    tags: ["accessible", "clear-approach", "four-seat-layout"],
  },
  {
    id: "item.standing-snack-ledge",
    name: "Standing Snack Ledge",
    description: "A narrow ledge for quick drinks and small plates without occupying a full seating bay.",
    category: "table",
    footprint: { width: 2, height: 1 },
    price: 160,
    level: 4,
    reputation: 20,
    ambience: 2,
    cleanliness: 0,
    tags: ["standing", "fast-turnover", "narrow"],
    service: { eatingSpeed: 0.12 },
  },
  {
    id: "item.folding-overflow-table",
    name: "Folding Overflow Table",
    description: "A practical folding table that is inexpensive to place for peak-period overflow seating.",
    category: "table",
    footprint: { width: 2, height: 1 },
    price: 125,
    level: 6,
    reputation: 28,
    ambience: -1,
    cleanliness: 0,
    tags: ["overflow", "budget", "portable"],
  },
  {
    id: "item.terrazzo-feature-table",
    name: "Terrazzo Feature Table",
    description: "A substantial terrazzo-topped table that raises ambience while remaining easy to wipe clean.",
    category: "table",
    footprint: { width: 2, height: 2 },
    price: 720,
    level: 11,
    reputation: 56,
    ambience: 12,
    cleanliness: 2,
    tags: ["premium", "durable", "four-seat-layout"],
    upkeep: 1,
  },

  // Seats: 10. Benches expose multiple seat anchors rather than counting recolours.
  {
    id: "item.stacking-stool",
    name: "Stacking Stool",
    description: "A simple, washable stool for compact, inexpensive starter seating.",
    category: "seat",
    footprint: { width: 1, height: 1 },
    price: 35,
    level: 1,
    reputation: 0,
    ambience: 0,
    cleanliness: 0,
    tags: ["starter", "compact", "backless"],
    seats: [{ x: 0, y: 0, facing: "north", comfort: 0.42, accessible: false }],
  },
  {
    id: "item.moulded-back-chair",
    name: "Moulded Back Chair",
    description: "A lightweight chair with back support and a wipe-clean moulded shell.",
    category: "seat",
    footprint: { width: 1, height: 1 },
    price: 60,
    level: 2,
    reputation: 8,
    ambience: 1,
    cleanliness: 0,
    tags: ["back-support", "washable", "single-seat"],
    seats: [{ x: 0, y: 0, facing: "north", comfort: 0.58, accessible: false }],
  },
  {
    id: "item.two-person-bench",
    name: "Two-Person Bench",
    description: "A fixed two-person bench that packs neatly along a communal table.",
    category: "seat",
    footprint: { width: 2, height: 1 },
    price: 115,
    level: 3,
    reputation: 14,
    ambience: 2,
    cleanliness: 0,
    tags: ["two-seat", "communal", "fixed"],
    seats: [
      { x: 0, y: 0, facing: "north", comfort: 0.52, accessible: false },
      { x: 1, y: 0, facing: "north", comfort: 0.52, accessible: false },
    ],
  },
  {
    id: "item.easy-rise-arm-chair",
    name: "Easy-Rise Arm Chair",
    description: "A firm chair with arm supports and open approach space for customers who value easier standing.",
    category: "seat",
    footprint: { width: 1, height: 1 },
    price: 130,
    level: 4,
    reputation: 22,
    ambience: 3,
    cleanliness: 0,
    tags: ["accessible", "arm-support", "senior-friendly"],
    seats: [{ x: 0, y: 0, facing: "north", comfort: 0.76, accessible: true }],
  },
  {
    id: "item.high-counter-stool",
    name: "High Counter Stool",
    description: "A tall stool sized for standing ledges and quick-turnover counter dining.",
    category: "seat",
    footprint: { width: 1, height: 1 },
    price: 75,
    level: 4,
    reputation: 20,
    ambience: 2,
    cleanliness: 0,
    tags: ["high-seat", "counter", "fast-turnover"],
    seats: [{ x: 0, y: 0, facing: "north", comfort: 0.46, accessible: false }],
    service: { eatingSpeed: 0.08 },
  },
  {
    id: "item.booster-family-chair",
    name: "Booster Family Chair",
    description: "A stable dining chair fitted with a secured child booster for family groups.",
    category: "seat",
    footprint: { width: 1, height: 1 },
    price: 105,
    level: 5,
    reputation: 25,
    ambience: 2,
    cleanliness: -1,
    tags: ["family", "child-seat", "secured"],
    seats: [{ x: 0, y: 0, facing: "north", comfort: 0.66, accessible: false }],
  },
  {
    id: "item.cushioned-dining-chair",
    name: "Cushioned Dining Chair",
    description: "A comfortable upholstered chair that encourages longer meals but needs more upkeep.",
    category: "seat",
    footprint: { width: 1, height: 1 },
    price: 145,
    level: 7,
    reputation: 34,
    ambience: 5,
    cleanliness: -1,
    tags: ["comfortable", "long-dwell", "upholstered"],
    seats: [{ x: 0, y: 0, facing: "north", comfort: 0.86, accessible: false }],
    upkeep: 1,
  },
  {
    id: "item.three-person-communal-bench",
    name: "Three-Person Communal Bench",
    description: "A long, robust bench providing three seats along high-capacity communal rows.",
    category: "seat",
    footprint: { width: 3, height: 1 },
    price: 210,
    level: 7,
    reputation: 36,
    ambience: 3,
    cleanliness: 0,
    tags: ["three-seat", "communal", "high-capacity"],
    seats: [
      { x: 0, y: 0, facing: "north", comfort: 0.54, accessible: false },
      { x: 1, y: 0, facing: "north", comfort: 0.54, accessible: false },
      { x: 2, y: 0, facing: "north", comfort: 0.54, accessible: false },
    ],
  },
  {
    id: "item.acoustic-booth-seat",
    name: "Acoustic Booth Seat",
    description: "A padded two-person booth back that dampens noise and creates a quieter dining pocket.",
    category: "seat",
    footprint: { width: 2, height: 1 },
    price: 390,
    level: 10,
    reputation: 50,
    ambience: 9,
    cleanliness: -1,
    tags: ["two-seat", "quiet", "premium"],
    seats: [
      { x: 0, y: 0, facing: "south", comfort: 0.9, accessible: false },
      { x: 1, y: 0, facing: "south", comfort: 0.9, accessible: false },
    ],
    upkeep: 1,
  },
  {
    id: "item.swivel-perch-seat",
    name: "Swivel Perch Seat",
    description: "A floor-fixed swivel seat for narrow counters, combining a small footprint with good back support.",
    category: "seat",
    footprint: { width: 1, height: 1 },
    price: 185,
    level: 12,
    reputation: 60,
    ambience: 5,
    cleanliness: 0,
    tags: ["counter", "swivel", "back-support"],
    seats: [{ x: 0, y: 0, facing: "north", comfort: 0.72, accessible: false }],
  },

  // Stall support fixtures: 8.
  {
    id: "item.queue-ticket-dispenser",
    name: "Queue Ticket Dispenser",
    description: "Issues visible order numbers so waiting customers can step aside without losing their place.",
    category: "stall-fixture",
    footprint: { width: 1, height: 1 },
    price: 280,
    level: 4,
    reputation: 22,
    ambience: 0,
    cleanliness: 0,
    tags: ["queue", "numbered-orders", "compact"],
    interactions: [{ x: 0, y: 1, role: "queue", facing: "north" }],
    queuePoints: [{ x: 0, y: 1 }, { x: 0, y: 2 }],
    service: { queuePatience: 0.08 },
    audio: [{ event: "fixture.ticket-print", volume: 0.22 }],
  },
  {
    id: "item.condiment-counter",
    name: "Condiment Counter",
    description: "Keeps covered chilli, sauces, utensils, and napkins together away from the collection point.",
    category: "stall-fixture",
    footprint: { width: 2, height: 1 },
    price: 190,
    level: 2,
    reputation: 10,
    ambience: 1,
    cleanliness: -1,
    tags: ["condiments", "self-service", "queue-relief"],
    interactions: [{ x: 0, y: 1, role: "use", facing: "north" }],
    service: { queuePatience: 0.02 },
  },
  {
    id: "item.cutlery-napkin-station",
    name: "Cutlery & Napkin Station",
    description: "A narrow self-service organiser for wrapped cutlery, chopsticks, spoons, and napkins.",
    category: "stall-fixture",
    footprint: { width: 1, height: 1 },
    price: 145,
    level: 3,
    reputation: 14,
    ambience: 0,
    cleanliness: 1,
    tags: ["cutlery", "self-service", "organised"],
    interactions: [{ x: 0, y: 1, role: "use", facing: "north" }],
  },
  {
    id: "item.water-carafe-station",
    name: "Water Carafe Station",
    description: "A sheltered counter with refillable carafes and cups for complimentary drinking water.",
    category: "stall-fixture",
    footprint: { width: 2, height: 1 },
    price: 260,
    level: 5,
    reputation: 26,
    ambience: 2,
    cleanliness: 1,
    tags: ["water", "self-service", "comfort"],
    interactions: [{ x: 0, y: 1, role: "collect-water", facing: "north" }],
    upkeep: 1,
  },
  {
    id: "item.order-pickup-shelf",
    name: "Order Pickup Shelf",
    description: "A clearly divided shelf that separates completed orders from the active service counter.",
    category: "stall-fixture",
    footprint: { width: 2, height: 1 },
    price: 340,
    level: 6,
    reputation: 30,
    ambience: 1,
    cleanliness: 1,
    tags: ["pickup", "throughput", "labelled-bays"],
    interactions: [{ x: 0, y: 1, role: "use", facing: "north" }],
    service: { queuePatience: 0.06 },
    audio: [{ event: "fixture.order-chime", volume: 0.2 }],
  },
  {
    id: "item.heated-display-case",
    name: "Heated Display Case",
    description: "A glass-fronted warmer that presents ready items while keeping the counter organised.",
    category: "stall-fixture",
    footprint: { width: 2, height: 1 },
    price: 620,
    level: 8,
    reputation: 40,
    ambience: 4,
    cleanliness: 1,
    tags: ["heated", "display", "ready-items"],
    interactions: [{ x: 0, y: 1, role: "use", facing: "north" }],
    animations: ["fixture.warmer-glow"],
    upkeep: 2,
    lightRadius: 1,
  },
  {
    id: "item.chilled-display-case",
    name: "Chilled Display Case",
    description: "A refrigerated glass case for drinks and chilled desserts with visible stock bays.",
    category: "stall-fixture",
    footprint: { width: 2, height: 1 },
    price: 780,
    level: 9,
    reputation: 46,
    ambience: 5,
    cleanliness: 1,
    tags: ["chilled", "display", "dessert"],
    interactions: [{ x: 0, y: 1, role: "use", facing: "north" }],
    animations: ["fixture.chiller-light"],
    audio: [{ event: "fixture.chiller-hum", volume: 0.12 }],
    upkeep: 3,
    lightRadius: 1,
  },
  {
    id: "item.mobile-prep-cart",
    name: "Mobile Prep Cart",
    description: "A lockable stainless-steel cart that extends a stall's staging space during busy periods.",
    category: "stall-fixture",
    footprint: { width: 2, height: 1 },
    price: 480,
    level: 10,
    reputation: 50,
    ambience: 0,
    cleanliness: 1,
    tags: ["mobile", "prep", "peak-support"],
    interactions: [{ x: 0, y: 1, role: "use", facing: "north" }],
    service: { queuePatience: 0.04 },
  },

  // Tray return and waste: 8.
  {
    id: "item.single-bay-tray-return",
    name: "Single-Bay Tray Return",
    description: "A compact, clearly marked rack for returning one stream of trays and crockery.",
    category: "tray-waste",
    footprint: { width: 2, height: 1 },
    price: 260,
    level: 1,
    reputation: 0,
    ambience: 0,
    cleanliness: 5,
    tags: ["tray-return", "starter", "single-stream"],
    interactions: [{ x: 0, y: 1, role: "return-tray", facing: "north" }],
    audio: [{ event: "facility.tray-slide", volume: 0.2 }],
  },
  {
    id: "item.dual-bay-tray-return",
    name: "Dual-Bay Tray Return",
    description: "Two return openings reduce crowding and separate trays from bowls and loose crockery.",
    category: "tray-waste",
    footprint: { width: 3, height: 1 },
    price: 520,
    level: 4,
    reputation: 22,
    ambience: 1,
    cleanliness: 9,
    tags: ["tray-return", "dual-stream", "high-throughput"],
    interactions: [
      { x: 0, y: 1, role: "return-tray", facing: "north" },
      { x: 2, y: 1, role: "return-tray", facing: "north" },
    ],
  },
  {
    id: "item.dish-drop-counter",
    name: "Dish Drop Counter",
    description: "A staffed-height return counter with separate tubs for bowls, plates, and cutlery.",
    category: "tray-waste",
    footprint: { width: 3, height: 1 },
    price: 690,
    level: 7,
    reputation: 34,
    ambience: 1,
    cleanliness: 11,
    tags: ["tray-return", "sorted-crockery", "staffed"],
    interactions: [{ x: 1, y: 1, role: "return-tray", facing: "north" }],
    service: { cleaningEfficiency: 0.1 },
    upkeep: 2,
  },
  {
    id: "item.recycling-sorter",
    name: "Recycling Sorter",
    description: "A labelled multi-stream station for cans, bottles, paper, and general waste.",
    category: "tray-waste",
    footprint: { width: 3, height: 1 },
    price: 440,
    level: 5,
    reputation: 26,
    ambience: 1,
    cleanliness: 6,
    tags: ["recycling", "labelled", "multi-stream"],
    interactions: [{ x: 1, y: 1, role: "dispose-waste", facing: "north" }],
  },
  {
    id: "item.covered-food-waste-bin",
    name: "Covered Food-Waste Bin",
    description: "A foot-pedal bin dedicated to food scraps, with a sealed lid and clear label.",
    category: "tray-waste",
    footprint: { width: 1, height: 1 },
    price: 180,
    level: 3,
    reputation: 16,
    ambience: -1,
    cleanliness: 5,
    tags: ["food-waste", "covered", "pedal"],
    interactions: [{ x: 0, y: 1, role: "dispose-waste", facing: "north" }],
  },
  {
    id: "item.general-waste-bin",
    name: "Covered General-Waste Bin",
    description: "A durable covered bin for non-recyclable waste, sized for dining-area use.",
    category: "tray-waste",
    footprint: { width: 1, height: 1 },
    price: 120,
    level: 1,
    reputation: 0,
    ambience: -1,
    cleanliness: 3,
    tags: ["general-waste", "covered", "starter"],
    interactions: [{ x: 0, y: 1, role: "dispose-waste", facing: "north" }],
  },
  {
    id: "item.cleaning-trolley-bay",
    name: "Cleaning Trolley Bay",
    description: "A recessed parking bay that keeps cleaning tools accessible without obstructing public aisles.",
    category: "tray-waste",
    footprint: { width: 2, height: 1 },
    price: 380,
    level: 6,
    reputation: 31,
    ambience: 0,
    cleanliness: 8,
    tags: ["cleaning", "staff", "storage"],
    service: { cleaningEfficiency: 0.15 },
  },
  {
    id: "item.clean-tray-stack-rack",
    name: "Clean Tray Stack Rack",
    description: "An open rack that keeps sanitised trays visible and ready near busy stall rows.",
    category: "tray-waste",
    footprint: { width: 1, height: 1 },
    price: 230,
    level: 4,
    reputation: 20,
    ambience: 0,
    cleanliness: 4,
    tags: ["clean-trays", "storage", "service"],
    interactions: [{ x: 0, y: 1, role: "use", facing: "north" }],
  },

  // Lighting: 7.
  {
    id: "item.ceiling-tube-light",
    name: "Efficient Ceiling Tube Light",
    description: "A bright, low-energy overhead strip that keeps service aisles clearly readable.",
    category: "lighting",
    footprint: { width: 2, height: 1 },
    price: 150,
    level: 1,
    reputation: 0,
    ambience: 1,
    cleanliness: 0,
    tags: ["bright", "efficient", "overhead"],
    walkability: "underpass",
    lightRadius: 5,
    upkeep: 1,
  },
  {
    id: "item.pendant-dining-light",
    name: "Pendant Dining Light",
    description: "A focused warm pendant that gives one dining cluster a comfortable pool of light.",
    category: "lighting",
    footprint: { width: 1, height: 1 },
    price: 220,
    level: 3,
    reputation: 14,
    ambience: 4,
    cleanliness: 0,
    tags: ["warm", "dining", "focused"],
    walkability: "underpass",
    lightRadius: 4,
    upkeep: 1,
  },
  {
    id: "item.woven-lantern-cluster",
    name: "Woven Lantern Cluster",
    description: "An original woven-shade cluster that adds a warm evening rhythm above communal tables.",
    category: "lighting",
    footprint: { width: 2, height: 2 },
    price: 440,
    level: 6,
    reputation: 30,
    ambience: 9,
    cleanliness: 0,
    tags: ["warm", "decorative", "cluster"],
    walkability: "underpass",
    lightRadius: 5,
    upkeep: 1,
  },
  {
    id: "item.counter-task-light",
    name: "Counter Task Light",
    description: "A slim, glare-controlled fitting that improves visibility across a stall service counter.",
    category: "lighting",
    footprint: { width: 2, height: 1 },
    price: 180,
    level: 2,
    reputation: 10,
    ambience: 1,
    cleanliness: 0,
    tags: ["counter", "task", "glare-controlled"],
    walkability: "underpass",
    lightRadius: 3,
    upkeep: 1,
  },
  {
    id: "item.low-path-light",
    name: "Low Path Light",
    description: "A shielded low-level light that marks expansion edges and routes without dazzling diners.",
    category: "lighting",
    footprint: { width: 1, height: 1 },
    price: 170,
    level: 5,
    reputation: 24,
    ambience: 2,
    cleanliness: 0,
    tags: ["wayfinding", "low-glare", "edge"],
    lightRadius: 2,
    upkeep: 1,
  },
  {
    id: "item.skylight-diffuser",
    name: "Skylight Diffuser",
    description: "A broad translucent ceiling panel that spreads simulated daylight over a large floor area.",
    category: "lighting",
    footprint: { width: 3, height: 3 },
    price: 780,
    level: 9,
    reputation: 46,
    ambience: 8,
    cleanliness: 0,
    tags: ["daylight", "broad", "low-energy"],
    walkability: "underpass",
    lightRadius: 7,
  },
  {
    id: "item.festive-string-lights",
    name: "Festive String Lights",
    description: "A restrained line of warm bulbs for celebratory atmosphere without blocking sightlines.",
    category: "lighting",
    footprint: { width: 4, height: 1 },
    price: 360,
    level: 8,
    reputation: 40,
    ambience: 10,
    cleanliness: 0,
    tags: ["festive", "warm", "linear"],
    walkability: "underpass",
    lightRadius: 4,
    animations: ["lighting.string-twinkle-subtle"],
    upkeep: 1,
  },

  // Fans and ventilation: 6.
  {
    id: "item.wall-circulation-fan",
    name: "Wall Circulation Fan",
    description: "An oscillating wall fan that improves airflow without consuming floor space.",
    category: "fan",
    footprint: { width: 1, height: 1 },
    price: 210,
    level: 2,
    reputation: 8,
    ambience: 1,
    cleanliness: 0,
    tags: ["wall-mounted", "oscillating", "airflow"],
    walkability: "underpass",
    animations: ["fan.wall-spin"],
    audio: [{ event: "fan.soft-hum", volume: 0.1 }],
    upkeep: 1,
    service: { queuePatience: 0.03 },
  },
  {
    id: "item.ceiling-fan",
    name: "Wide Ceiling Fan",
    description: "A slow, broad ceiling fan that cools a communal seating zone with minimal visual clutter.",
    category: "fan",
    footprint: { width: 3, height: 3 },
    price: 390,
    level: 4,
    reputation: 20,
    ambience: 3,
    cleanliness: 0,
    tags: ["ceiling", "broad-airflow", "quiet"],
    walkability: "underpass",
    animations: ["fan.ceiling-spin"],
    audio: [{ event: "fan.soft-hum", volume: 0.08 }],
    upkeep: 1,
    service: { queuePatience: 0.05, eatingSpeed: 0.02 },
  },
  {
    id: "item.column-fan",
    name: "Column Fan",
    description: "A slim floor fan that targets a narrow row of tables and can fit beside structural columns.",
    category: "fan",
    footprint: { width: 1, height: 1 },
    price: 280,
    level: 5,
    reputation: 25,
    ambience: 1,
    cleanliness: 0,
    tags: ["floor", "targeted-airflow", "slim"],
    animations: ["fan.column-oscillate"],
    audio: [{ event: "fan.medium-hum", volume: 0.12 }],
    upkeep: 1,
    service: { queuePatience: 0.04 },
  },
  {
    id: "item.high-volume-air-fan",
    name: "High-Volume Air Fan",
    description: "A large industrial fan that cools a broad busy zone at the cost of more noise and power.",
    category: "fan",
    footprint: { width: 2, height: 2 },
    price: 720,
    level: 8,
    reputation: 40,
    ambience: -2,
    cleanliness: 0,
    tags: ["industrial", "broad-airflow", "powerful"],
    animations: ["fan.hvaf-spin"],
    audio: [{ event: "fan.industrial-hum", volume: 0.2 }],
    upkeep: 3,
    service: { queuePatience: 0.09, movementSpeed: 0.02 },
  },
  {
    id: "item.quiet-corner-fan",
    name: "Quiet Corner Fan",
    description: "A low-noise bladeless fan designed for calmer seating pockets and accessible routes.",
    category: "fan",
    footprint: { width: 1, height: 1 },
    price: 540,
    level: 10,
    reputation: 50,
    ambience: 5,
    cleanliness: 0,
    tags: ["quiet", "accessible-route", "targeted-airflow"],
    animations: ["fan.quiet-airflow"],
    audio: [{ event: "fan.soft-hum", volume: 0.05 }],
    upkeep: 2,
    service: { queuePatience: 0.06 },
  },
  {
    id: "item.stall-exhaust-booster",
    name: "Stall Exhaust Booster",
    description: "A duct-mounted extractor that reduces lingering cooking haze around high-heat stalls.",
    category: "fan",
    footprint: { width: 2, height: 1 },
    price: 880,
    level: 11,
    reputation: 56,
    ambience: 2,
    cleanliness: 4,
    tags: ["extraction", "stall-support", "air-quality"],
    walkability: "underpass",
    animations: ["fan.exhaust-flow"],
    audio: [{ event: "fan.extractor", volume: 0.14 }],
    upkeep: 3,
    service: { queuePatience: 0.04 },
  },

  // Plants: 8 distinct scales and placement jobs.
  {
    id: "item.table-herb-planter",
    name: "Table Herb Planter",
    description: "A small tabletop planter of hardy culinary herbs that adds greenery without occupying an aisle.",
    category: "plant",
    footprint: { width: 1, height: 1 },
    price: 75,
    level: 2,
    reputation: 8,
    ambience: 3,
    cleanliness: 0,
    tags: ["tabletop", "herbs", "small"],
    walkability: "underpass",
    upkeep: 1,
  },
  {
    id: "item.tall-areca-planter",
    name: "Tall Areca Planter",
    description: "A tall indoor palm planter that softens hard edges and marks the entrance to a seating zone.",
    category: "plant",
    footprint: { width: 1, height: 1 },
    price: 190,
    level: 3,
    reputation: 15,
    ambience: 6,
    cleanliness: 1,
    tags: ["tall", "zone-marker", "tropical"],
    upkeep: 1,
  },
  {
    id: "item.fern-trough",
    name: "Fern Trough",
    description: "A low linear trough of ferns that separates circulation from dining without blocking views.",
    category: "plant",
    footprint: { width: 3, height: 1 },
    price: 310,
    level: 5,
    reputation: 24,
    ambience: 8,
    cleanliness: 1,
    tags: ["linear", "low", "soft-divider"],
    upkeep: 1,
  },
  {
    id: "item.vine-trellis",
    name: "Vine Trellis",
    description: "A slim climbing trellis that provides a green backdrop and partial visual screening.",
    category: "plant",
    footprint: { width: 2, height: 1 },
    price: 360,
    level: 6,
    reputation: 30,
    ambience: 10,
    cleanliness: 1,
    tags: ["climbing", "screen", "backdrop"],
    upkeep: 2,
  },
  {
    id: "item.rain-garden-pot",
    name: "Rain-Garden Pot",
    description: "A broad planted pot with moisture-loving foliage, suited to open edges and entrance courts.",
    category: "plant",
    footprint: { width: 2, height: 2 },
    price: 420,
    level: 7,
    reputation: 34,
    ambience: 11,
    cleanliness: 2,
    tags: ["broad", "entrance", "rain-garden"],
    upkeep: 2,
  },
  {
    id: "item.hanging-pothos",
    name: "Hanging Pothos Basket",
    description: "A trailing hanging plant that adds overhead greenery while leaving the floor clear.",
    category: "plant",
    footprint: { width: 1, height: 1 },
    price: 155,
    level: 4,
    reputation: 20,
    ambience: 5,
    cleanliness: 0,
    tags: ["hanging", "trailing", "floor-clear"],
    walkability: "underpass",
    upkeep: 1,
  },
  {
    id: "item.dwarf-banana-planter",
    name: "Dwarf Banana Planter",
    description: "A lush broad-leaf planter that creates a strong green focal point in a larger dining court.",
    category: "plant",
    footprint: { width: 2, height: 2 },
    price: 520,
    level: 9,
    reputation: 46,
    ambience: 14,
    cleanliness: 1,
    tags: ["broad-leaf", "focal", "tropical"],
    upkeep: 2,
  },
  {
    id: "item.pandan-border-bed",
    name: "Pandan Border Bed",
    description: "A neat raised bed of pandan plants that defines a long edge with a recognisable local garden plant.",
    category: "plant",
    footprint: { width: 4, height: 1 },
    price: 610,
    level: 10,
    reputation: 52,
    ambience: 13,
    cleanliness: 2,
    tags: ["linear", "border", "pandan"],
    upkeep: 2,
  },

  // Signage and wayfinding: 7.
  {
    id: "item.entrance-directory",
    name: "Entrance Directory",
    description: "A high-contrast centre map showing stall rows, tray returns, washing points, and accessible routes.",
    category: "signage",
    footprint: { width: 2, height: 1 },
    price: 240,
    level: 2,
    reputation: 10,
    ambience: 2,
    cleanliness: 0,
    tags: ["directory", "high-contrast", "wayfinding"],
    interactions: [{ x: 0, y: 1, role: "inspect-menu", facing: "north" }],
    service: { movementSpeed: 0.03 },
  },
  {
    id: "item.stall-row-marker",
    name: "Stall Row Marker",
    description: "A suspended row letter and arrow that helps visitors scan several stalls from a distance.",
    category: "signage",
    footprint: { width: 2, height: 1 },
    price: 145,
    level: 3,
    reputation: 14,
    ambience: 1,
    cleanliness: 0,
    tags: ["row", "arrow", "overhead"],
    walkability: "underpass",
    service: { movementSpeed: 0.02 },
  },
  {
    id: "item.tray-return-arrow-sign",
    name: "Tray-Return Arrow Sign",
    description: "A prominent arrow and tray symbol directing diners to the nearest return station.",
    category: "signage",
    footprint: { width: 1, height: 1 },
    price: 95,
    level: 1,
    reputation: 0,
    ambience: 0,
    cleanliness: 2,
    tags: ["tray-return", "pictogram", "directional"],
    walkability: "underpass",
  },
  {
    id: "item.accessible-wayfinding-sign",
    name: "Accessible Route Sign",
    description: "A high-contrast directional sign marking step-free routes, clear approaches, and accessible seating.",
    category: "signage",
    footprint: { width: 1, height: 1 },
    price: 120,
    level: 3,
    reputation: 16,
    ambience: 1,
    cleanliness: 0,
    tags: ["accessible", "high-contrast", "directional"],
    walkability: "underpass",
    service: { movementSpeed: 0.03 },
  },
  {
    id: "item.queue-etiquette-sign",
    name: "Queue Courtesy Sign",
    description: "A friendly pictogram sign asking waiting diners to keep the cross-aisle and collection point clear.",
    category: "signage",
    footprint: { width: 1, height: 1 },
    price: 105,
    level: 4,
    reputation: 20,
    ambience: 1,
    cleanliness: 0,
    tags: ["queue", "pictogram", "courtesy"],
    walkability: "underpass",
    service: { queuePatience: 0.03, movementSpeed: 0.02 },
  },
  {
    id: "item.menu-preview-board",
    name: "Menu Preview Board",
    description: "A freestanding board that shows representative dishes and prices before customers join a queue.",
    category: "signage",
    footprint: { width: 1, height: 1 },
    price: 190,
    level: 5,
    reputation: 25,
    ambience: 2,
    cleanliness: 0,
    tags: ["menu", "prices", "queue-decision"],
    interactions: [{ x: 0, y: 1, role: "inspect-menu", facing: "north" }],
    service: { queuePatience: 0.04 },
  },
  {
    id: "item.centre-identity-sign",
    name: "Centre Identity Sign",
    description: "A large original centre-name sign that creates a memorable entrance landmark without real-world branding.",
    category: "signage",
    footprint: { width: 4, height: 1 },
    price: 680,
    level: 9,
    reputation: 46,
    ambience: 12,
    cleanliness: 0,
    tags: ["identity", "entrance", "landmark"],
    walkability: "underpass",
    lightRadius: 2,
    upkeep: 1,
  },

  // Dividers and queue control: 6.
  {
    id: "item.low-timber-screen",
    name: "Low Timber Screen",
    description: "A waist-high slatted screen that separates zones while preserving sightlines and airflow.",
    category: "divider",
    footprint: { width: 3, height: 1 },
    price: 240,
    level: 3,
    reputation: 14,
    ambience: 4,
    cleanliness: 0,
    tags: ["low", "slatted", "zone-divider"],
  },
  {
    id: "item.tiled-half-wall",
    name: "Tiled Half Wall",
    description: "A robust washable half wall for shielding dining areas from service and cleaning zones.",
    category: "divider",
    footprint: { width: 3, height: 1 },
    price: 360,
    level: 5,
    reputation: 24,
    ambience: 5,
    cleanliness: 2,
    tags: ["washable", "solid", "service-screen"],
  },
  {
    id: "item.clear-wind-screen",
    name: "Clear Wind Screen",
    description: "A transparent panel that reduces drafts near perimeter seats while retaining visual openness.",
    category: "divider",
    footprint: { width: 3, height: 1 },
    price: 410,
    level: 6,
    reputation: 30,
    ambience: 3,
    cleanliness: -1,
    tags: ["transparent", "draft-control", "perimeter"],
    upkeep: 1,
  },
  {
    id: "item.integrated-planter-divider",
    name: "Integrated Planter Divider",
    description: "A sturdy low divider topped with greenery, combining route control with a strong ambience boost.",
    category: "divider",
    footprint: { width: 3, height: 1 },
    price: 520,
    level: 8,
    reputation: 40,
    ambience: 10,
    cleanliness: 1,
    tags: ["greenery", "route-control", "low"],
    upkeep: 2,
  },
  {
    id: "item.retractable-queue-rail",
    name: "Retractable Queue Rail",
    description: "A flexible three-position belt rail that makes a queue shape clear without building a permanent wall.",
    category: "divider",
    footprint: { width: 3, height: 1 },
    price: 210,
    level: 2,
    reputation: 10,
    ambience: 0,
    cleanliness: 0,
    tags: ["queue", "retractable", "flexible"],
    queuePoints: [{ x: 0, y: 1 }, { x: 1, y: 1 }, { x: 2, y: 1 }],
    service: { queuePatience: 0.06 },
  },
  {
    id: "item.acoustic-screen",
    name: "Acoustic Screen",
    description: "A tall sound-absorbing panel that creates a quieter pocket beside noisy service equipment.",
    category: "divider",
    footprint: { width: 2, height: 1 },
    price: 620,
    level: 11,
    reputation: 56,
    ambience: 8,
    cleanliness: 0,
    tags: ["quiet", "sound-absorbing", "tall"],
    upkeep: 1,
  },

  // Practical facilities: 7.
  {
    id: "item.public-handwash-sink",
    name: "Public Handwash Sink",
    description: "A clearly signed sink with soap, touch-light taps, and a splashback for diners to wash their hands.",
    category: "facility",
    footprint: { width: 2, height: 1 },
    price: 480,
    level: 1,
    reputation: 0,
    ambience: 1,
    cleanliness: 8,
    tags: ["handwashing", "hygiene", "public"],
    interactions: [{ x: 0, y: 1, role: "wash-hands", facing: "north" }],
    audio: [{ event: "facility.tap-water", volume: 0.16 }],
    upkeep: 2,
  },
  {
    id: "item.drinking-water-fountain",
    name: "Drinking-Water Fountain",
    description: "A bottle-refill and drinking-water point with clear controls and a drip tray.",
    category: "facility",
    footprint: { width: 1, height: 1 },
    price: 390,
    level: 4,
    reputation: 20,
    ambience: 2,
    cleanliness: 2,
    tags: ["drinking-water", "bottle-refill", "public"],
    interactions: [{ x: 0, y: 1, role: "collect-water", facing: "north" }],
    audio: [{ event: "facility.water-fill", volume: 0.14 }],
    upkeep: 2,
  },
  {
    id: "item.locked-cleaning-cupboard",
    name: "Locked Cleaning Cupboard",
    description: "A staff-only cupboard that stores chemicals and tools securely away from public circulation.",
    category: "facility",
    footprint: { width: 2, height: 1 },
    price: 320,
    level: 3,
    reputation: 16,
    ambience: 0,
    cleanliness: 6,
    tags: ["staff-only", "secure", "cleaning-storage"],
    service: { cleaningEfficiency: 0.08 },
  },
  {
    id: "item.staff-mop-sink",
    name: "Staff Mop Sink",
    description: "A deep staff sink with tool clips and drainage for faster, tidier floor-cleaning cycles.",
    category: "facility",
    footprint: { width: 2, height: 1 },
    price: 560,
    level: 6,
    reputation: 30,
    ambience: -1,
    cleanliness: 10,
    tags: ["staff-only", "floor-care", "drainage"],
    service: { cleaningEfficiency: 0.18 },
    upkeep: 2,
  },
  {
    id: "item.first-aid-cabinet",
    name: "First-Aid Cabinet",
    description: "A visible, wall-mounted staff first-aid cabinet placed clear of heat and wet areas.",
    category: "facility",
    footprint: { width: 1, height: 1 },
    price: 180,
    level: 2,
    reputation: 10,
    ambience: 0,
    cleanliness: 0,
    tags: ["staff", "safety", "wall-mounted"],
    walkability: "underpass",
  },
  {
    id: "item.accessible-wash-basin",
    name: "Accessible Wash Basin",
    description: "A lower basin with knee clearance, lever controls, and a clear front approach.",
    category: "facility",
    footprint: { width: 2, height: 1 },
    price: 640,
    level: 7,
    reputation: 36,
    ambience: 2,
    cleanliness: 9,
    tags: ["accessible", "handwashing", "clear-approach"],
    interactions: [{ x: 0, y: 1, role: "wash-hands", facing: "north" }],
    audio: [{ event: "facility.tap-water", volume: 0.14 }],
    upkeep: 2,
  },
  {
    id: "item.protected-utility-point",
    name: "Protected Utility Point",
    description: "A lockable power and data pedestal for temporary equipment, positioned away from wet facilities.",
    category: "facility",
    footprint: { width: 1, height: 1 },
    price: 450,
    level: 9,
    reputation: 46,
    ambience: 0,
    cleanliness: 0,
    tags: ["power", "temporary-equipment", "lockable"],
    upkeep: 1,
  },

  // Decorative objects: 5, each with a different placement scale and visual job.
  {
    id: "item.geometric-tile-mural",
    name: "Geometric Tile Mural",
    description: "An original abstract tile composition inspired by breeze, shade, and shared tables rather than copied motifs.",
    category: "decor",
    footprint: { width: 4, height: 1 },
    price: 560,
    level: 6,
    reputation: 30,
    ambience: 12,
    cleanliness: 0,
    tags: ["wall-art", "original-pattern", "focal"],
    walkability: "underpass",
  },
  {
    id: "item.community-noticeboard",
    name: "Community Noticeboard",
    description: "A cork-and-enamel board for fictional neighbourhood events, opening times, and helpful centre notices.",
    category: "decor",
    footprint: { width: 2, height: 1 },
    price: 230,
    level: 3,
    reputation: 16,
    ambience: 5,
    cleanliness: 0,
    tags: ["community", "notices", "wall-mounted"],
    walkability: "underpass",
  },
  {
    id: "item.fabric-ceiling-bunting",
    name: "Fabric Ceiling Bunting",
    description: "Reusable fabric pennants in the centre's own palette, hung high enough to preserve clear routes and sightlines.",
    category: "decor",
    footprint: { width: 4, height: 1 },
    price: 280,
    level: 5,
    reputation: 24,
    ambience: 8,
    cleanliness: 0,
    tags: ["ceiling", "celebration", "reusable"],
    walkability: "underpass",
    animations: ["decor.bunting-gentle"],
  },
  {
    id: "item.tabletop-flower-vase",
    name: "Tabletop Flower Vase",
    description: "A small shatter-resistant vase of seasonal flowers that lifts one table's ambience.",
    category: "decor",
    footprint: { width: 1, height: 1 },
    price: 95,
    level: 4,
    reputation: 20,
    ambience: 4,
    cleanliness: 0,
    tags: ["tabletop", "flowers", "small"],
    walkability: "underpass",
    upkeep: 1,
  },
  {
    id: "item.feature-centre-clock",
    name: "Feature Centre Clock",
    description: "A large, legible clock with quiet hands that becomes a useful meeting landmark.",
    category: "decor",
    footprint: { width: 2, height: 1 },
    price: 420,
    level: 8,
    reputation: 40,
    ambience: 9,
    cleanliness: 0,
    tags: ["clock", "landmark", "legible"],
    walkability: "underpass",
    animations: ["decor.clock-minute-tick"],
  },
] as const satisfies readonly PlaceableInput[];

const occupiedTiles = (width: number, height: number): readonly GridPoint[] => {
  const points: GridPoint[] = [];
  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) points.push({ x, y });
  }
  return points;
};

const asPlaceable = (input: PlaceableInput): PlaceableDefinition => {
  const rotations = input.rotations ?? ([0, 90, 180, 270] as const);
  const walkability = input.walkability ?? "blocked";
  const interactionPoints = input.interactions ?? [];
  const seatPoints = input.seats ?? [];

  return {
    id: input.id,
    nameKey: `item.${input.id.slice("item.".length)}.name`,
    descriptionKey: `item.${input.id.slice("item.".length)}.description`,
    category: input.category,
    footprint: input.footprint,
    rotations,
    price: input.price,
    resaleValue: Math.max(1, Math.floor(input.price * 0.6)),
    upkeepPerMinute: input.upkeep ?? 0,
    unlockRequirement: {
      level: input.level,
      reputation: input.reputation,
      prerequisiteIds: input.prerequisiteIds ?? [],
    },
    walkability,
    collision:
      walkability === "blocked"
        ? occupiedTiles(input.footprint.width, input.footprint.height)
        : [],
    interactionPoints:
      interactionPoints.length > 0
        ? interactionPoints
        : seatPoints.map((seat) => ({
            x: seat.x,
            y: seat.y,
            role: "sit" as const,
            facing: seat.facing,
          })),
    seatPoints,
    queuePoints: input.queuePoints ?? [],
    pivot: { x: input.footprint.width / 2, y: input.footprint.height },
    depthSortAnchor: { x: input.footprint.width / 2, y: input.footprint.height },
    spriteReferences: rotations.map((rotation) => ({
      atlas: `placeables-${input.category}`,
      frame: `${input.id.slice("item.".length)}-r${rotation}`,
    })),
    animationReferences: input.animations ?? [],
    audioReferences: input.audio ?? [],
    ambienceValue: input.ambience,
    cleanlinessModifier: input.cleanliness,
    serviceModifiers: {
      queuePatience: input.service?.queuePatience ?? 0,
      eatingSpeed: input.service?.eatingSpeed ?? 0,
      cleaningEfficiency: input.service?.cleaningEfficiency ?? 0,
      movementSpeed: input.service?.movementSpeed ?? 0,
    },
    lightRadius: input.lightRadius ?? 0,
    tags: input.tags,
  };
};

export const PLACEABLES: readonly PlaceableDefinition[] =
  placeableInputs.map(asPlaceable);

export const PLACEABLE_ENGLISH: Readonly<Record<string, string>> =
  Object.fromEntries(
    placeableInputs.flatMap((item) => [
      [`item.${item.id.slice("item.".length)}.name`, item.name],
      [`item.${item.id.slice("item.".length)}.description`, item.description],
    ]),
  );

export const PLACEABLE_CATEGORY_MINIMUMS = {
  table: 8,
  seat: 10,
  "stall-fixture": 8,
  "tray-waste": 8,
  lighting: 7,
  fan: 6,
  plant: 8,
  signage: 7,
  divider: 6,
  facility: 7,
  decor: 5,
} as const satisfies Readonly<Record<PlaceableCategory, number>>;
