import type {
  LocalizedSeed,
  StallDefinition,
  StallUpgradeLevel,
} from "./types";

type StallSeed = Omit<StallDefinition, "nameKey" | "descriptionKey"> &
  LocalizedSeed;

const upgrades = (baseCost: number): readonly StallUpgradeLevel[] => [
  {
    level: 2,
    cost: baseCost,
    serviceTimeMultiplier: 0.9,
    capacityBonus: 1,
    qualityBonus: 0.04,
    menuSlotsBonus: 0,
  },
  {
    level: 3,
    cost: Math.round(baseCost * 1.75),
    serviceTimeMultiplier: 0.8,
    capacityBonus: 1,
    qualityBonus: 0.07,
    menuSlotsBonus: 1,
  },
  {
    level: 4,
    cost: Math.round(baseCost * 2.7),
    serviceTimeMultiplier: 0.7,
    capacityBonus: 2,
    qualityBonus: 0.1,
    menuSlotsBonus: 1,
  },
];

const stallSeeds = [
  {
    id: "stall.sunrise-roost",
    name: "Sunrise Roost",
    description:
      "A bright rice stall centred on gently poached and roasted chicken, clear broth, and quick breakfast service.",
    cuisineTags: ["chicken-rice", "comfort", "breakfast"],
    footprint: { width: 4, height: 3 },
    servicePoint: { x: 1, y: 3 },
    queueAnchor: { x: 1, y: 3 },
    queueDirection: "south",
    menuSlots: 3,
    dishIds: [
      "dish.poached-chicken-rice",
      "dish.roast-chicken-rice",
      "dish.soya-tofu-rice",
      "dish.chicken-congee",
    ],
    serviceTimeMs: 5_000,
    preparationCapacity: 4,
    quality: 0.68,
    popularity: 0.76,
    purchaseCost: 1_200,
    operatingCostPerMinute: 3,
    upgradeLevels: upgrades(720),
    unlockRequirement: { level: 1, reputation: 0, prerequisiteIds: [] },
    visual: {
      sprite: { atlas: "stalls", frame: "sunrise-roost" },
      palette: ["#F4C95D", "#FFF3D0", "#3C6E71"],
      signShape: "awning",
      counterFacing: "south",
      depthSortAnchor: { x: 2, y: 3 },
    },
    animationReferences: ["stall.common.idle", "stall.chop.prepare", "stall.plate.serve"],
    audioReferences: [
      { event: "stall.chopping-soft", volume: 0.36 },
      { event: "stall.crockery", volume: 0.28 },
    ],
    tags: ["starter", "fast-service", "low-smoke"],
  },
  {
    id: "stall.coconut-lime",
    name: "Coconut & Lime",
    description:
      "A welcoming Malay-inspired counter serving coconut rice, aromatic gravies, noodles, and warming soups.",
    cuisineTags: ["malay", "rice", "soup", "spice"],
    footprint: { width: 4, height: 3 },
    servicePoint: { x: 2, y: 3 },
    queueAnchor: { x: 2, y: 3 },
    queueDirection: "south",
    menuSlots: 3,
    dishIds: ["dish.nasi-lemak", "dish.mee-rebus", "dish.soto-ayam", "dish.lontong-sayur"],
    serviceTimeMs: 5_700,
    preparationCapacity: 3,
    quality: 0.7,
    popularity: 0.72,
    purchaseCost: 1_350,
    operatingCostPerMinute: 3,
    upgradeLevels: upgrades(780),
    unlockRequirement: { level: 1, reputation: 0, prerequisiteIds: [] },
    visual: {
      sprite: { atlas: "stalls", frame: "coconut-lime" },
      palette: ["#3A7D44", "#F2E8CF", "#D98E32"],
      signShape: "painted-board",
      counterFacing: "south",
      depthSortAnchor: { x: 2, y: 3 },
    },
    animationReferences: ["stall.common.idle", "stall.ladle.prepare", "stall.bowl.serve"],
    audioReferences: [
      { event: "stall.simmer", volume: 0.32 },
      { event: "stall.ladle", volume: 0.26 },
    ],
    tags: ["starter", "balanced-service", "aromatic"],
  },
  {
    id: "stall.kopi-canopy",
    name: "Kopi Canopy",
    description:
      "A compact drinks and dessert stall pouring local-style coffee and tea alongside fresh juice and shaved ice.",
    cuisineTags: ["drinks", "dessert", "kopitiam"],
    footprint: { width: 3, height: 2 },
    servicePoint: { x: 1, y: 2 },
    queueAnchor: { x: 1, y: 2 },
    queueDirection: "south",
    menuSlots: 3,
    dishIds: ["dish.kopi", "dish.sugarcane-juice", "dish.ice-kacang"],
    serviceTimeMs: 3_800,
    preparationCapacity: 5,
    quality: 0.64,
    popularity: 0.69,
    purchaseCost: 1_800,
    operatingCostPerMinute: 2,
    upgradeLevels: upgrades(900),
    unlockRequirement: {
      level: 2,
      reputation: 10,
      prerequisiteIds: ["stall.sunrise-roost"],
    },
    visual: {
      sprite: { atlas: "stalls", frame: "kopi-canopy" },
      palette: ["#6F4E37", "#A8DADC", "#F7E1AE"],
      signShape: "lightbox",
      counterFacing: "south",
      depthSortAnchor: { x: 1, y: 2 },
    },
    animationReferences: ["stall.common.idle", "stall.pour.prepare", "stall.cup.serve"],
    audioReferences: [
      { event: "stall.pour", volume: 0.32 },
      { event: "stall.ice-shave", volume: 0.25 },
    ],
    tags: ["compact", "very-fast-service", "dessert"],
  },
  {
    id: "stall.cinder-wok",
    name: "Cinder Wok",
    description:
      "A high-heat wok stall preparing beloved noodle and griddle dishes one fragrant batch at a time.",
    cuisineTags: ["wok", "noodles", "seafood", "savoury"],
    footprint: { width: 4, height: 3 },
    servicePoint: { x: 2, y: 3 },
    queueAnchor: { x: 2, y: 3 },
    queueDirection: "south",
    menuSlots: 3,
    dishIds: [
      "dish.char-kway-teow",
      "dish.hokkien-prawn-mee",
      "dish.fried-carrot-cake",
      "dish.oyster-omelette",
    ],
    serviceTimeMs: 7_600,
    preparationCapacity: 2,
    quality: 0.75,
    popularity: 0.82,
    purchaseCost: 2_200,
    operatingCostPerMinute: 5,
    upgradeLevels: upgrades(1_050),
    unlockRequirement: {
      level: 3,
      reputation: 16,
      prerequisiteIds: ["stall.sunrise-roost"],
    },
    visual: {
      sprite: { atlas: "stalls", frame: "cinder-wok" },
      palette: ["#C44536", "#22223B", "#F2CC8F"],
      signShape: "tile-panel",
      counterFacing: "south",
      depthSortAnchor: { x: 2, y: 3 },
    },
    animationReferences: ["stall.common.idle", "stall.wok-toss.cook", "stall.plate.serve"],
    audioReferences: [
      { event: "stall.wok-sizzle", volume: 0.45 },
      { event: "stall.metal-spatula", volume: 0.3 },
    ],
    tags: ["batch-cooking", "popular", "smoke-effect"],
  },
  {
    id: "stall.tiffin-lantern",
    name: "Tiffin Lantern",
    description:
      "An Indian-Muslim-inspired stall working a hot griddle and stockpots for breads, noodles, rice, and filled murtabak.",
    cuisineTags: ["indian-muslim", "griddle", "rice", "bread"],
    footprint: { width: 4, height: 3 },
    servicePoint: { x: 1, y: 3 },
    queueAnchor: { x: 1, y: 3 },
    queueDirection: "south",
    menuSlots: 3,
    dishIds: ["dish.roti-prata", "dish.mee-goreng-mamak", "dish.chicken-murtabak", "dish.nasi-briyani"],
    serviceTimeMs: 7_000,
    preparationCapacity: 3,
    quality: 0.76,
    popularity: 0.78,
    purchaseCost: 2_600,
    operatingCostPerMinute: 5,
    upgradeLevels: upgrades(1_200),
    unlockRequirement: {
      level: 5,
      reputation: 24,
      prerequisiteIds: ["stall.cinder-wok"],
    },
    visual: {
      sprite: { atlas: "stalls", frame: "tiffin-lantern" },
      palette: ["#E07A5F", "#F4F1DE", "#3D405B"],
      signShape: "awning",
      counterFacing: "south",
      depthSortAnchor: { x: 2, y: 3 },
    },
    animationReferences: ["stall.common.idle", "stall.griddle.cook", "stall.tiffin.serve"],
    audioReferences: [
      { event: "stall.griddle", volume: 0.4 },
      { event: "stall.dough-slap", volume: 0.28 },
    ],
    tags: ["mixed-menu", "medium-service", "griddle"],
  },
  {
    id: "stall.tamarind-leaf",
    name: "Tamarind Leaf",
    description:
      "A South Indian vegetarian stall pairing fermented batters, lentil dishes, and rice with sambar and chutneys.",
    cuisineTags: ["south-indian", "vegetarian", "lentil", "rice"],
    footprint: { width: 4, height: 3 },
    servicePoint: { x: 2, y: 3 },
    queueAnchor: { x: 2, y: 3 },
    queueDirection: "south",
    menuSlots: 3,
    dishIds: ["dish.masala-thosai", "dish.idli-sambar", "dish.vadai-set", "dish.lemon-rice"],
    serviceTimeMs: 6_400,
    preparationCapacity: 3,
    quality: 0.78,
    popularity: 0.71,
    purchaseCost: 3_100,
    operatingCostPerMinute: 4,
    upgradeLevels: upgrades(1_350),
    unlockRequirement: {
      level: 7,
      reputation: 34,
      prerequisiteIds: ["stall.tiffin-lantern"],
    },
    visual: {
      sprite: { atlas: "stalls", frame: "tamarind-leaf" },
      palette: ["#606C38", "#FEFAE0", "#DDA15E"],
      signShape: "painted-board",
      counterFacing: "south",
      depthSortAnchor: { x: 2, y: 3 },
    },
    animationReferences: ["stall.common.idle", "stall.griddle-spread.cook", "stall.leaf.serve"],
    audioReferences: [
      { event: "stall.griddle-soft", volume: 0.34 },
      { event: "stall.ladle", volume: 0.24 },
    ],
    tags: ["vegetarian-menu", "steady-service", "breakfast"],
  },
  {
    id: "stall.straits-hearth",
    name: "Straits Hearth",
    description:
      "A Peranakan-inspired kitchen offering carefully braised, spiced, and coconut-rich dishes with a slower, quality-led service.",
    cuisineTags: ["peranakan", "braise", "spice", "heritage"],
    footprint: { width: 5, height: 3 },
    servicePoint: { x: 2, y: 3 },
    queueAnchor: { x: 2, y: 3 },
    queueDirection: "south",
    menuSlots: 3,
    dishIds: ["dish.nyonya-laksa", "dish.ayam-buah-keluak", "dish.chap-chye", "dish.babi-pongteh"],
    serviceTimeMs: 8_100,
    preparationCapacity: 2,
    quality: 0.86,
    popularity: 0.74,
    purchaseCost: 3_800,
    operatingCostPerMinute: 6,
    upgradeLevels: upgrades(1_600),
    unlockRequirement: {
      level: 9,
      reputation: 46,
      prerequisiteIds: ["stall.tamarind-leaf"],
    },
    visual: {
      sprite: { atlas: "stalls", frame: "straits-hearth" },
      palette: ["#2A9D8F", "#F4A261", "#264653"],
      signShape: "tile-panel",
      counterFacing: "south",
      depthSortAnchor: { x: 2, y: 3 },
    },
    animationReferences: ["stall.common.idle", "stall.braise.prepare", "stall.bowl.serve"],
    audioReferences: [
      { event: "stall.simmer", volume: 0.36 },
      { event: "stall.crockery", volume: 0.25 },
    ],
    tags: ["premium-quality", "slow-service", "braised"],
  },
  {
    id: "stall.harbour-ember",
    name: "Harbour Ember",
    description:
      "A seafood-focused grill and soup stall balancing smoky sambal dishes with clear, comforting fish soup.",
    cuisineTags: ["seafood", "grill", "soup", "premium"],
    footprint: { width: 5, height: 3 },
    servicePoint: { x: 3, y: 3 },
    queueAnchor: { x: 3, y: 3 },
    queueDirection: "south",
    menuSlots: 3,
    dishIds: ["dish.sambal-stingray", "dish.black-pepper-crab", "dish.sliced-fish-soup"],
    serviceTimeMs: 9_000,
    preparationCapacity: 2,
    quality: 0.9,
    popularity: 0.83,
    purchaseCost: 4_700,
    operatingCostPerMinute: 8,
    upgradeLevels: upgrades(1_900),
    unlockRequirement: {
      level: 12,
      reputation: 62,
      prerequisiteIds: ["stall.straits-hearth"],
    },
    visual: {
      sprite: { atlas: "stalls", frame: "harbour-ember" },
      palette: ["#1D3557", "#E63946", "#F1FAEE"],
      signShape: "lightbox",
      counterFacing: "south",
      depthSortAnchor: { x: 3, y: 3 },
    },
    animationReferences: ["stall.common.idle", "stall.chargrill.cook", "stall.platter.serve"],
    audioReferences: [
      { event: "stall.grill-sizzle", volume: 0.44 },
      { event: "stall.steam", volume: 0.26 },
    ],
    tags: ["premium", "slow-service", "strong-aroma"],
  },
] as const satisfies readonly StallSeed[];

export const STALLS: readonly StallDefinition[] = stallSeeds.map(
  ({ name, description, ...stall }) => {
    void name;
    void description;
    return {
      ...stall,
      nameKey: `stall.${stall.id.slice("stall.".length)}.name`,
      descriptionKey: `stall.${stall.id.slice("stall.".length)}.description`,
    };
  },
);

export const STALL_ENGLISH: Readonly<Record<string, string>> = Object.fromEntries(
  stallSeeds.flatMap((stall) => [
    [`stall.${stall.id.slice("stall.".length)}.name`, stall.name],
    [`stall.${stall.id.slice("stall.".length)}.description`, stall.description],
  ]),
);
